### ISSUE TITLE
android:fullBackupContent build issue when using custom backup rules

### ISSUE THREAD

**Issue by MagicMiikka** [AppsFlyerSDK/appsflyer-unity-plugin#10]
We use android:fullBackupContent="@xml/my_backup_rules" as a workaround for unity related crashes when the app is installed from a backup (Google Drive etc).

Is there a proper way to integrate the backups needed by AppsFlyer?
I will try to use override in the main manifest next.

Here are our my_backup_rules.xml:

```
<full-backup-content>
    <!-- Explicitly including files to backup because of crash with restored Unity "il2cpp" folder.
         Using "exclude" in any way does not prevent "il2cpp" from being restored (equals app crash).
         Combining "include" "." and "exclude" "il2cpp" does not prevent the restore of "il2cpp".
         Using only "include" does prevent a restore of "il2cpp". -->
    <include domain="sharedpref" path="."/>
</full-backup-content>
```

**Comment by MagicMiikka** [comment]
using replace in the manifest indeed works around this problem.
Ideally having the requirements (full-backup-content) defined by AppsFlyer would make it more resonable as then it can be just appended to the my_backup_rules.xml with comments where each rule is originating from.

**Comment by wesfieldj** [comment]
@MagicMiikka Please see this article from the AppsFlyer knowledge base - https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-backup-rules

As you can see the backup rules are supported and can be added by updating your manifest to include  -

```xml
<full-backup-content>
    ...//your custom rules
    <exclude domain="sharedpref" path="appsflyer-data"/>
</full-backup-content>
```

**Comment by MagicMiikka** [comment]
Thanks this is exactly what I was looking for.
