### ISSUE TITLE
SDK Integration Test Failing on iOS 14.5

### ISSUE THREAD

**Issue by GSRicky** [AppsFlyerSDK/appsflyer-unity-plugin#100]
**Tested on**
Unity: 2018.2.21f1 and 2019.2.21f1
AppsFlyer SDK: 6.2.0
Swizzling Enabled for Firebase/Facebook SDK Compatibility

**Issue**
When running the console SDK Integration Test (Non-Organic Install) on iOS 14.5 we cannot get the ‘successfully tracked app launch’ result in most instances:

(Issue Case) Start Integration Test -> Install app from **AppStore** -> Launch app -> AppsFlyer SDK started -> tester agrees to App Tracking Transparency -> AppsFlyer SDK Init method called -> Integration Test fails to detect install
(Issue Case) Start Integration Test -> Install app from **TestFlight** -> Launch app -> AppsFlyer SDK started -> tester agrees to App Tracking Transparency -> AppsFlyer SDK Init method called -> Integration Test fails to detect install

The only case that works as expected is if we run the app directly from XCode, with no other changes.

(Non-Issue Case) Start Integration Test -> Install app from **XCode** -> Launch app -> AppsFlyer SDK started -> tester agrees to App Tracking Transparency -> AppsFlyer SDK Init method called -> Integration test successfully tracks launch.

100% reproduction rate in all instances. No issues on Android or other versions of iOS.

The Xcode test suggests our implementation is working as expected and we cannot easily further debug TestFlight or live builds.

There are no additional instructions in the Unity SDK installation guide for iOS 14.5 support. Based on the iOS SDK integration guide, we implemented waiting for the user response from App Tracking Transparency before AppsFlyer SDK initialization. Prior to implementing this, the iOS 14.5 integration test failed in all instances.

**Comment by af-margot** [comment]
HI @GSRicky, 
Thank you for reaching out! 
Please look at this [doc](https://support.appsflyer.com/hc/en-us/articles/360011890298-Quickstart-guide-FAQ-to-iOS-14-ATT-and-SKAdNetwork), maybe this could help!
Otherwise, please open a ticket to our [support team](support@appsflyer.com) as this does not seem directly related to Unity. They will be able to help you with all questions for iOS 14.5.

**Comment by james-b-kelly** [comment]
I'm also having this issue (not related to Unity) but can't find any documentation related (the referenced doc above doesn't help).  The support team link leads to a blank GitHub page.
