### ISSUE TITLE
Can't pass the "Non Organic install" SDK integration test

### ISSUE THREAD

**Issue by Skyway666** [AppsFlyerSDK/appsflyer-unity-plugin#108]
### VERSIONS
Unity version: 2019.4.9f1
Plugin version: 6.3.2

### ISSUE

Hi, I'm trying to use AppsFlyer in order to keep track of the installs count in my Unity game. The first milestone that I would like to accomplish is passing the SDK integration test, but even if the Unity plugin seems to be well installed and configured, since I followed all the steps in [this](https://support.appsflyer.com/hc/en-us/articles/360007314277-Unity-plugin-V6-integration-guide-for-developers#integration) guide, it still doesn't work.

### WHAT I'VE DONE SO FAR

- Install the appsflyer plugin Unity package, avoiding the installation of the EDM since I already had it in my project
- Set up the android permissions in the "AndroidManifest.xml" (INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE), which is located in Assets/Plugins/Google/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin.

![AndroidManifest](https://user-images.githubusercontent.com/16372100/125957394-e1a7bcaf-8d08-4ebc-9bb9-2fd3b0e087af.PNG)

- Drag the "AppsFlyerObject" prefab to the scene, as a child of an object that has the "Don'tDestroyOnLoad" flag.
- Use External Dependency Manager to resolve all possible dependencies by calling "Resolve"
- The game is only targeted towards Android, so the only parameter I'm providing the AppsFlyerObjectScript is the DevKey, which I get from my AppsFlyer dashboard (as indicated in the guide). I've double checked that the parameter is correct.
- I've made a release for android, and used the "getSdkVersion()" function, which logs out the expected value.
- Both the "initSDK" and "startSDK" fucntions are being called. However, even if the "IsDebug" flag is activated, no log appears on the console when I call this functions, it kind of feels like nothing is happening.
- By activating the "GetConversionData" flag, I get an error message:

![Error log](https://user-images.githubusercontent.com/16372100/125956782-bc48000c-9404-4ecc-9a14-52ba0a45d38b.jpeg)

"AppsFlyer_Unity_v6.3.2 didReceiveConversionDataWithError called with Launch status code: 404"

I'm not interested in "deepLinking" yet, but maybe this error gives you a clue of what might be causing the plugin to not work.

### WHAT I WOULD LIKE

Please, help me understand what part of the configuration process I might be doing wrong, or wich alternatives I have in order to comunicate with the AppsFlyer service in order to pass the SDK integration test.

Thank you very much.

**Comment by pazlavi** [comment]
Hi @Skyway666 , 
Thank you for reaching out to us. 

You got the error code 404 because there is no dashboard exist for the app ID `com.google.example.games.mainlibproj`.
If you have any further questions, please submit a ticket to our support team  at support@appsflyer.com
