### ISSUE TITLE
UWP initialization fails if Get Conversion Data is false.

### ISSUE THREAD

**Issue by SplenectomY** [AppsFlyerSDK/appsflyer-unity-plugin#112]
UWP code expects gameObject in AppsFlyerWindows.InitSDK, but gameObject is set to null in AppsFlyerObjectScript.Start if AppsFlyerObjectScript.getConversionData is false.

![image](https://user-images.githubusercontent.com/4369778/126993152-9ac9ff5e-8c0a-4318-a4d4-d007358cc3de.png)

![image](https://user-images.githubusercontent.com/4369778/126993189-20cb6eb8-1225-4d50-bcf7-77693d39ba3d.png)

![image](https://user-images.githubusercontent.com/4369778/126993231-040a934f-3811-4138-94ca-4e8b466e7bd4.png)

![image](https://user-images.githubusercontent.com/4369778/126993268-af40ce1c-b7a5-4555-8f7b-fffed8c5e8e7.png)

This is where the issue happens, as no null check is being made for gameObject, despite it being set to null if AppsFlyerObjectScript.getConversionData is false.

If getConversionData MUST be on for UWP builds, then it should be enforced via code. Otherwise, the proper null checks must be made to avoid this null reference exception.

**Comment by af-margot** [comment]
Hi @SplenectomY, 

Thank you for the input! 
It seems only the log is the issue here. As the rest won't be called if `gameObject` is null. We will double-check it and include the fix in the next release.

**Comment by SplenectomY** [comment]
@af-margot There's actually a few places in the script that can fail if _gameObject is null ( Consult the pull request I created to see all the examples at https://github.com/SplenectomY/appsflyer-unity-plugin/commit/1b37fae23cf77f80e68c33716a2fb1ffa9876764), BUT I didn't dig deep enough to see if checks for GetConversionData are made prior to any other references to _gameObject. Definitely worth a good look and testing with GetConversionData = false just to be sure.

**Comment by af-margot** [comment]
Hi @SplenectomY, 

Yes, we will check it thoroughly before making the fix! 
Thank you again for the input! 👍

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
