### ISSUE TITLE
UWP: nullref exception when sending event if eventdata is null

### ISSUE THREAD

**Issue by SplenectomY** [AppsFlyerSDK/appsflyer-unity-plugin#114]
Eventdata can be passed as null in Android and iOS, and this situation is handled correctly in that code. For Windows, however, the code fails here:

![image](https://user-images.githubusercontent.com/4369778/127038318-bc0f30fe-7df1-44d5-98cb-7d1098543eec.png)

Leading to this:

![image](https://user-images.githubusercontent.com/4369778/127038347-16a1aed0-755f-4763-987a-51661989b7e5.png)

Here's a simple fix I will be submitting as a pull request so this doesn't break others' code that uses null for non-needed event data:

![image](https://user-images.githubusercontent.com/4369778/127038430-bf36b6c9-74ba-458d-913e-ce494f422bb4.png)

**Comment by af-margot** [comment]
Hi @SplenectomY , 

Thank you for this input! 
Indeed, we will change it for the next release. In the meantime, if you don't want to pass eventValues you can pass an empty dictionary!

**Comment by SplenectomY** [comment]
Yep, I'm currently passing in an empty dictionary as my workaround in the meantime. Thanks!

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
