### ISSUE TITLE
Android init fails. java.lang.NoSuchMethodError no static method with name='startTracking'

### ISSUE THREAD

**Issue by gromilQaaaa** [AppsFlyerSDK/appsflyer-unity-plugin#116]
Hello, we use release 6.2.61. It. fails on android. I see that AppsFlyerAndroid script still uses "startTracking" even knowing that since V6 it was renamed to "start" as said in here https://support.appsflyer.com/hc/en-us/articles/115001256006-AppsFlyer-Android-SDK-release-notes

Latest release 6.3.2 still has the issue. Please give this priority, it is blocking android development.
![image](https://user-images.githubusercontent.com/5392680/127166519-48bf7d83-4ab3-4b7e-99b3-4a30d68e95b8.png)
![image](https://user-images.githubusercontent.com/5392680/127166538-4cc9fe09-4bfb-4c79-af1d-8c3a3ecade21.png)
![image](https://user-images.githubusercontent.com/5392680/127166560-9344fff4-c3cf-4ec3-b8fc-1e31c949e212.png)

**Comment by af-margot** [comment]
HI @gromilQaaaa,

I think you are missing the **android-unity-wrapper**. 
The `startTracking` comes from [there](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/android-unity-wrapper/unitywrapper/src/main/java/com/appsflyer/unity/AppsFlyerAndroidWrapper.java#L52). 

How did you install the plugin ?

**Comment by gromilQaaaa** [comment]
Yeah, sorry. Thank you
