### ISSUE TITLE
DynamicLinks Conflict with Firebase

### ISSUE THREAD

**Issue by gromilQaaaa** [AppsFlyerSDK/appsflyer-unity-plugin#12]
Please check this topic:
https://github.com/firebase/quickstart-unity/issues/626

Long story short:
Using both Appsflyer and Firebase dynamic links leads to both overwriting one ios method and not using it's super/base version. Dynamic links don't work.

**Comment by wesfieldj** [comment]
@gromilQaaaa Thanks for reporting this issue.

We are aware of possible conflicts with other plugins, so we created a workaround for this built into the plugin. 

In Assets>AppsFlyer>Plugins>iOS there exists a class [AppsFlyer+AppController.m](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyer%2BAppController.m#L2)

This class is used for optional sizzling, to solve conflicts with other plugins. 
To use this you need to comment out the necessary code.
In your case you need to make the following changes :
1. Remove the comments [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyer%2BAppController.m#L53) and [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyer%2BAppController.m#L60)
2. Comment out the continueUserActivity method [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyerAppController.mm#L60)


This should solve the conflicts with firebase dynamic links. 

(Also take note, when updated the plugin in unity these changes can be lost)

Please let us know if it does not work or if you are facing any other issues. 

Thanks!

**Comment by gromilQaaaa** [comment]
This solution about adding [super] call seem to fix the problem
https://github.com/firebase/quickstart-unity/issues/626#issuecomment-612060018

**Comment by wesfieldj** [comment]
@gromilQaaaa makes sense. We will add the super call in the next release. 
 We also plan to add the plugin to UPM soon. 


Thanks!

**Comment by gromilQaaaa** [comment]
idk if this is still the same issue, but I got some errors on Android that may lead to crash sometimes:
`AppsFlyer_5.3.0: An error occurred while trying to verify manifest declarations: 
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzc extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.gamepoint.bingo-2/base.apk:classes2.dex)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.lang.Class.classForName(Native Method)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.lang.Class.forName(Class.java:400)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.lang.Class.forName(Class.java:326)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at com.appsflyer.internal.al.ι(:20)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at com.appsflyer.AppsFlyerLibCore.ı(:2035)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at com.appsflyer.AppsFlyerLibCore.Ι(:1588)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at com.appsflyer.AppsFlyerLibCore.ι(:93)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at com.appsflyer.AppsFlyerLibCore$b.run(:3284)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at com.appsflyer.AFExecutor$1$3.run(:31)
05-07 15:05:04.201 27927 28253 E AppsFlyer_5.3.0: 	at java.lang.Thread.run(Thread.java:776)
05-07 15:05:04.223 27927 28253 I AppsFlyer_5.3.0: AppsFlyerLib.sendTrackingWithEvent
`
and
`05-07 15:05:04.199 27927 28253 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzc extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.gamepoint.bingo-2/base.apk:classes2.dex)
05-07 15:05:04.200 27927 28253 I art     :   at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
05-07 15:05:04.200 27927 28253 I art     :   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
05-07 15:05:04.200 27927 28253 I art     :   at java.lang.Class java.lang.Class.forName(java.lang.String) (Class.java:326)
05-07 15:05:04.200 27927 28253 I art     :   at boolean com.appsflyer.internal.al.ι(android.content.Context) (:20)
05-07 15:05:04.200 27927 28253 I art     :   at java.util.Map com.appsflyer.AppsFlyerLibCore.ı(com.appsflyer.AFEvent) (:2035)
05-07 15:05:04.200 27927 28253 I art     :   at void com.appsflyer.AppsFlyerLibCore.Ι(com.appsflyer.AFEvent) (:1588)
05-07 15:05:04.200 27927 28253 I art     :   at void com.appsflyer.AppsFlyerLibCore.ι(com.appsflyer.AppsFlyerLibCore, com.appsflyer.AFEvent) (:93)
05-07 15:05:04.200 27927 28253 I art     :   at void com.appsflyer.AppsFlyerLibCore$b.run() (:3284)
05-07 15:05:04.200 27927 28253 I art     :   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:428)
05-07 15:05:04.200 27927 28253 I art     :   at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
05-07 15:05:04.200 27927 28253 I art     :   at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:272)
05-07 15:05:04.200 27927 28253 I art     :   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
05-07 15:05:04.200 27927 28253 I art     :   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
05-07 15:05:04.200 27927 28253 I art     :   at void com.appsflyer.AFExecutor$1$3.run() (:31)
05-07 15:05:04.200 27927 28253 I art     :   at void java.lang.Thread.run() (Thread.java:776)`

**Comment by wesfieldj** [comment]
@gromilQaaaa The changes to support dynamic links were added in v5.3.1
