### ISSUE TITLE
Tag 'Strict-v6.4.1' missing

### ISSUE THREAD

**Issue by mpartel** [AppsFlyerSDK/appsflyer-unity-plugin#128]
v6.4.1 was released, but it looks like the strict version was not.

**Comment by ge-af** [comment]
Hi @mpartel 

Thank you for reaching out!

The Strict mode variant was updated yesterday to v6.4.1 as well. It can be found [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/tree/master/strict-mode-sdk).

Please let us know if you have any additional issues.

**Comment by mpartel** [comment]
The branch has been updated but the git tag `Strict-v6.4.1` is missing.

**Comment by af-margot** [comment]
Hi @mpartel , 
The [tag](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/releases/tag/Strict-v6.4.1) has been pushed.
