### ISSUE TITLE
Question about the API "AppsFlyeriOS.setUseReceiptValidationSandbox" 

### ISSUE THREAD

**Issue by li5414** [AppsFlyerSDK/appsflyer-unity-plugin#131]
![Snipaste_2021-11-24_16-03-03](https://user-images.githubusercontent.com/8327631/143198547-6c1631fd-02eb-4dbb-a52c-37bf4c713d0b.png)

The sandbox environment should not be set by developer, it should be handled automatically by the server

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
