### ISSUE TITLE
Deferred deeplink reported as direct on iOS when testing

### ISSUE THREAD

**Issue by SeriouslySam** [AppsFlyerSDK/appsflyer-unity-plugin#134]
Using the Unity SDK 6.2.61.

When testing the UDL deeplinking, we noticed that the case for deferred deeplink is always reported as direct on iOS. On Android this works as expected. Specifically, the deepLinkEventArgs.isDeferred() returns false even if we'd expect it to return true.

Steps to return:
- Don't have app on device
- Click the deeplink url on device
- Link redirects to app store as expected
- Use xcode to install the app
- Start the app. Deeplink data is received in the app but the isDeferred returns false.

I'm not 100% if this is a testing issue, didn't find documentation to suggest otherwise, so please advice also if this requires some other more specific way of testing to detect the deferred status correctly.

**Comment by af-margot** [comment]
Hi @SeriouslySam,

Thank you for your patience here.
There is a fix for it in the new release [v6.4.41](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/releases/tag/6.4.41) !
