### ISSUE TITLE
AppsFlyer SDK Error with unity 3D

### ISSUE THREAD

**Issue by NamanSemalti** [AppsFlyerSDK/appsflyer-unity-plugin#142]
![Error](https://user-images.githubusercontent.com/72019184/151525054-da55a382-366e-4472-84ec-dcefe3968338.PNG)

Hey guys, I was integrating AppsFlyers SDK on my unity project and as I tried to build my game, my Unity Console showed me the above errors. 
I would be thankful to you if you have solution to this problem.

**Comment by af-margot** [comment]
HI @NamanSemalti, 

The issue is quite old, but in case you are still experiencing it, could you try to resolve the dependencies?
Go to Assets/External Dependency Manager/Android Resolver/Resolve
