### ISSUE TITLE
Strict v6.5.2 missing

### ISSUE THREAD

**Issue by snorrsi** [AppsFlyerSDK/appsflyer-unity-plugin#143]
hi @af-margot ,

it seems that Strict-v6.5.2 has not been created, only v6.5.2

Can you please create Strict-v6.5.2 tag ?

best regards,
Snorri

**Comment by af-margot** [comment]
Thank you !
It was just [created](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/releases/tag/Strict-v6.5.2)

**Comment by snorrsi** [comment]
Hi @af-margot ,

thanks.. I can however see that the package.json file has not been updated (8 month old), it was updated in Strict-v6.4.41 and should be updated for this release as well I would think (to represent correct version number in Unity)

**Comment by af-margot** [comment]
Updated it on the [branch](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/Strict-upm/package.json)

**Comment by snorrsi** [comment]
Hi @af-margot ,

the package is not without errors.
I get 4 errors in Unity, related to [Assets/AppsFlyer/Editor](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/tree/Strict-v6.5.2/Assets/AppsFlyer/Editor)
Asset Packages/appsflyer-unity-plugin/Assets has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/appsflyer-unity-plugin/Assets/AppsFlyer has no meta file, but it's in an immutable folder. The asset will be ignored. .. and so on

I see this symlink is not in Strict-v6.4.41
Can you remove this Assets/AppsFlyer/Editor reference ?

**Comment by af-margot** [comment]
Sure, let me know if its working for you now

**Comment by snorrsi** [comment]
Hi @af-margot ,

thanks.. seems to be working fine now, yet to test on device though.
