### ISSUE TITLE
Installation doc references package registry that no longer exists

### ISSUE THREAD

**Issue by trdillon** [AppsFlyerSDK/appsflyer-unity-plugin#144]
The [installation doc](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Installation.md#-using-unity-package-manager) for the UPM package instructs the user to add the Game Package Registry by Google to their package manifest:

  2. Add Google game package registery fpr the external dependency Manager.

 ``` 
"scopedRegistries": [
    {
      "name": "Game Package Registry by Google",
      "url": "https://unityregistry-pa.googleapis.com",
      "scopes": [
        "com.google"
      ]
    }
  ]
```

This registry no longer exists due to changes in the Unity TOS that made some or all of the packages non-compliant. 

Google offers their UPM packages in the following archive now:
https://developers.google.com/unity/archive

**Comment by af-margot** [comment]
Thank you for the input, we will investigate the issue!
