### ISSUE TITLE
Unable to build for Android because of conflicting androidx.multidex dependencies in 6.5.2

### ISSUE THREAD

**Issue by shobhit-samaria** [AppsFlyerSDK/appsflyer-unity-plugin#145]
Hi. I had to include AppsFlyer in a project as a requirement. I downloaded the v6.5.2 unitypackage and imported it into project successfully. However after the addition of the SDK, I was unable to build the project for Android. I kept getting "Duplicate Classes" error.

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class androidx.multidex.BuildConfig found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V14 found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V14$ElementConstructor found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V14$ICSElementConstructor found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V14$JBMR11ElementConstructor found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V14$JBMR2ElementConstructor found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V19 found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDex$V4 found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDexApplication found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDexExtractor found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDexExtractor$1 found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.MultiDexExtractor$ExtractedDex found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.ZipUtil found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
  Duplicate class androidx.multidex.ZipUtil$CentralDirectory found in modules jetified-androidx.multidex.multidex-2.0.0-runtime.jar (:androidx.multidex.multidex-2.0.0:) and multidex-2.0.1-runtime.jar (androidx.multidex:multidex:2.0.1)
`

After fiddling around a lot, I finally found that there are 3 dependencies in AppsFlyerDependencies.xml - af-android-sdk, unity-wrapper, com.android.installreferrer. It seems that both af-android-sdk and installreferrer dependencies add the androidx.multidex dependency resulting in a conflict. I was able to build successfully if I turned off either of the two dependencies. But that obviously is not a solution.

The workaround was to remove v6.5.2 and use v6.4.0 and it worked perfectly out of the box the first time itself. This lends me to believe that there may be an issue with the latest version. Can someone please look into it? Happy to be corrected if I have missed any step while installing the sdk or while building the project which is causing this issue.

**Comment by runing-five-flower-meat** [comment]
https://www.jianshu.com/p/28244c379ece

**Comment by af-margot** [comment]
HI @shobhit-samaria,

Indeed, you need the three dependencies to work. 
Could you try resolving the dependencies? Go to Assets/External Dependency Manager/Android Resolver/Resolve

**Comment by griever-gf** [comment]
I have the same issue. Any help?
