### ISSUE TITLE
Build fails due to duplicate classes (EasyMobile)

### ISSUE THREAD

**Issue by Legacycz** [AppsFlyerSDK/appsflyer-unity-plugin#147]
Hello, we're using Unity 2020.3.26 and our project uses EasyMobile (2.18.0) plugin.
The AppsFlyer is integrated with UPM and the External Dependency Manager seems to work fine if I invoke "Force Resolve". But the build fails due to following error. Any help how to solve this would be appretiated.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class kotlin.ArrayIntrinsicsKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.BuilderInference found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Deprecated found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.DeprecationLevel found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.DslMarker found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ExceptionsKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ExceptionsKt__ExceptionsKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Experimental found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Experimental$Level found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ExperimentalMultiplatform found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ExperimentalStdlibApi found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ExperimentalUnsignedTypes found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ExtensionFunctionType found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Function found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.HashCodeKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.InitializedLazyImpl found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.KotlinNullPointerException found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.KotlinVersion found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.KotlinVersion$Companion found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.LateinitKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Lazy found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.LazyKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.LazyKt$WhenMappings found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.LazyKt__LazyJVMKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.LazyKt__LazyKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.LazyThreadSafetyMode found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Metadata found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NoWhenBranchMatchedException found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NotImplementedError found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NumbersKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NumbersKt__BigDecimalsKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NumbersKt__BigIntegersKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NumbersKt__NumbersJVMKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.NumbersKt__NumbersKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.OptionalExpectation found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Pair found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ParameterName found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.PreconditionsKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.PreconditionsKt__AssertionsJVMKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.PreconditionsKt__PreconditionsKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.PublishedApi found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ReplaceWith found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Result found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Result$Companion found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Result$Failure found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.ResultKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.SafePublicationLazyImpl found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.SafePublicationLazyImpl$Companion found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.SinceKotlin found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.StandardKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.StandardKt__StandardKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.StandardKt__SynchronizedKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Suppress found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.SuspendKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.SynchronizedLazyImpl found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.Triple found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.TuplesKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.TypeAliasesKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.TypeCastException found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UByte found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UByte$Companion found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UByteArray found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UByteArray$Iterator found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UByteArrayKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UByteKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UInt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UInt$Companion found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UIntArray found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UIntArray$Iterator found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)
  Duplicate class kotlin.UIntArrayKt found in modules app-1.6.2-unity-runtime.jar (:app-1.6.2-unity:) and org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar (org.jetbrains.kotlin.kotlin-stdlib-1.4.21.jar)

**Comment by af-margot** [comment]
Hi, 

If you are still experiencing this issue, please open a Support ticket at [support@appsflyer.com](mailto:support@appsflyer.com) with all the relevant information and we will be more than glad to supply the assistance needed.
