### ISSUE TITLE
Non-SDK API Usage Violation - Unity Project build with AppsFlyer SDK - v.6.5.3

### ISSUE THREAD

**Issue by Kris-AT** [AppsFlyerSDK/appsflyer-unity-plugin#150]
The project is built on Unity Platform.
Unity Version - 2020.3.10f1 - LTS version.
Using the package and testing on Firebase robo testing, I get these issues.

The issue in-specific starts from API 28 & 28+. The lower versions do not have these issues

> Your app uses 5 non-SDK interfaces, which are incompatible with Android P+.
> 
> 
> 
> Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement;
> 
> Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application;
> 
> Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V
> 
> Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList;
> 
> Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List;
> 

Can you let know how to overcome this issue?

**Comment by af-margot** [comment]
Hi @Kris-AT,

Which version of the Appsflyer plugin are you using? Could you give more details of why you think this issue is related to AppsFlyer?
