### ISSUE TITLE
I have user this sdk but it never shows non-orgainic installs , can you please tell me what might be the problem?

### ISSUE THREAD

**Issue by vin-spiegel** [AppsFlyerSDK/appsflyer-unity-plugin#156]
When a non-organic test is performed, a log is displayed on the dashboard. However, when the service is actually performed, non-organic is not recorded.

**Comment by af-margot** [comment]
Hi,

If you are still experiencing this issue, please open a Support ticket at [support@appsflyer.com](mailto:support@appsflyer.com) with all the relevant information and we will be more than glad to supply the assistance needed.
