### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by UnVoiding** [AppsFlyerSDK/appsflyer-unity-plugin#164]
Hello,

Is there a changelog for the plugin? If you haven't got any you should start doing it. 

Like why you deleted AppsFlyerAdRevenue and there is no single word about it?

**Comment by af-margot** [comment]
Hi @UnVoiding,

Thank you for reaching out!
You can find our changelog [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/CHANGELOG.md). 

About `AppsFlyerAdRevenue`, it is part of another [repo](https://github.com/AppsFlyerSDK/appsflyer-unity-adrevenue-connector). As mentioned there, this repo was deprecated and moved to a new repo [here](https://github.com/AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector). 
Hope this is more clear now !
