### ISSUE TITLE
AppsFlyer.getConversionData method does't work as expected.

### ISSUE THREAD

**Issue by Antonio-Iliev** [AppsFlyerSDK/appsflyer-unity-plugin#166]
Hello team,

Thank you for the Unity AppsFlyer integration plugin.

I try to get Conversion Data on the application startup, but when invoking the method AppsFlyer.getConversionData("GObj name") the listener doesn't receive anything. I need to 'send' the application in background and then when I bring it back (the application becomes in focus) I received the Conversion Data. I need only to invoke the method once, after that every time when the application is in background and then in focus again I receive the Conversion Data.

My setup is:
Unity - 2020.3.31
AppsFlyerPluginVersion - 6.6.1
SDK initialization - Using AppsFlyerObject.prefab in the scene for initialization.
Test device - Android Xiaomi Redmi 10 2022

If you can help me to get data as I call for it, I'll be very thankful.

**Comment by af-margot** [comment]
Hi @Antonio-Iliev,

Thank you for reaching out !
Please open a ticket to our [support@appsflyer.com](mailto:support@appsflyer.com) with the previous info, code snippet of the AppsFlyer Integration, and some logs if possible. They will be able to further help you!

Thank you !

**Comment by Antonio-Iliev** [comment]
Hi @af-margot,
Thank you!
