### ISSUE TITLE
Can't build on iOS with strict-6.8.1

### ISSUE THREAD

**Issue by Swah** [AppsFlyerSDK/appsflyer-unity-plugin#170]
Just a heads up that a dependency path seems malformed and prevented us from building on iOS:

AppsFlyer\Editor\AppsFlyerDependencies.xml
        `<iosPod name="AppsFlyerFramework/Strict/Strict" version="6.8.1" minTargetSdk="9.0">`
should be 
        `<iosPod name="AppsFlyerFramework/Strict" version="6.8.1" minTargetSdk="9.0">`

This fixes the problem for us.

**Comment by af-margot** [comment]
Hi @Swah , 

Thank you for reaching out! This was fixed in the new version.
