### ISSUE TITLE
Missing Strict-v6.8.4 and dependency confusion

### ISSUE THREAD

**Issue by snorrsi** [AppsFlyerSDK/appsflyer-unity-plugin#179]
Hi @af-margot and @af-do  ,

I notice that v6.8.4 tag has been created but not Strict-v6.8.4

There is also one thing I noticed it's that in Strict-v6.5.2 the Pod dependency
changed from AppsFlyerFramework/Strict to AppsFlyerFramework and has been that ever since and still is.
Have you stopped using the AppsFlyerFramework/Strict ?

https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/Strict-v6.4.41/Editor/AppsFlyerDependencies.xml
vs
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/Strict-v6.8.3/Editor/AppsFlyerDependencies.xml

**Comment by af-margot** [comment]
Hi @snorrsi ,

Thank you for reaching out!
We are still using `AppsFlyerFramework/Strict ` 
I fixed the dependency for the strict mode in [v6.8.3 ](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/Strict-v6.8.3/Editor/AppsFlyerDependencies.xml)

v6.8.4 was not released with upm, as the fix only concerned the unitypackage. If you are using upm, you can use v6.8.3 as the latest version. 
Thank you!

**Comment by af-margot** [comment]
Hi @snorrsi,

I added v6.8.4 and upm also in order to align it. 
`v6.8.4` for the regular mode and `Strict-v6.8.4` for the strict mode. You can find the tags [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/tags).
