### ISSUE TITLE
Android can't build with Vungle sdk

### ISSUE THREAD

**Issue by ikitae** [AppsFlyerSDK/appsflyer-unity-plugin#18]
Manifest merger failed : Attribute application@fullBackupContent value=(@xml/appsflyer_backup_rules) from [com.appsflyer:af-android-sdk:5.3.0] AndroidManifest.xml:14:18-73
	is also present at [com.vungle:publisher-sdk-android:6.5.3] AndroidManifest.xml:19:9-60 value=(@xml/vungle_backup_rule).
	Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:4:3-38:17 to override.

**Comment by wesfieldj** [comment]
@ikitae Can you please take a look at this - https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android#integration-backup-rules

Can you try to see if the fix described in the article solves the issue for you?

Thanks!
