### ISSUE TITLE
AppsFlyerSDK.IAppsFlyerNativeBridge.attributeAndOpenStore marked as iOS only, after 6.6

### ISSUE THREAD

**Issue by IoannisFMG** [AppsFlyerSDK/appsflyer-unity-plugin#180]
Hi!
We recently had to update the appsflyer SDK version from 6.4 to 6.8 and I see that the `AppsFlyerSDK.IAppsFlyerNativeBridge.attributeAndOpenStore` stopped working on Android devices.
Searching the code revealed that the call has been marked as iOS only in the Android Bridge file.

I have checked the Android and Unity plugin changelogs and I saw no reference or reason this might have happened. 
I also saw that the native code that actually handles that is still in the java file, only the bridge doesn't call it.

Was this marked as iOS only erroneously? Did something change without being documented?

**Comment by af-margot** [comment]
Hi,

Thank you for reaching out!
It seems that it is indeed an error, we will investigate it. If the error is confirmed, we will fix it and include it in one of our next releases. 
In the meantime, please reach out to our [support@appsflyer.com](mailto:support@appsflyer.com). They will be able to help you with relevant questions about this matter.

**Comment by IoannisFMG** [comment]
The most easy way to fix this, as far as I see, is to just call the other `attributeAndOpenStore` from the exposed one.

```
public void attributeAndOpenStore(string appID, string campaign, Dictionary<string, string> userParams, MonoBehaviour gameObject)
        {
            attributeAndOpenStore(appID, campaign, userParams);
        }
```

Other ways would require refactoring and/or optional parameters.

**Comment by af-margot** [comment]
Hi @IoannisFMG,

You can implement this solution in the meantime until we are releasing the next version.
