### ISSUE TITLE
GameObject (9) bug

### ISSUE THREAD

**Issue by SnaiperoG3D** [AppsFlyerSDK/appsflyer-unity-plugin#181]
If initialization script is used with gameobject named GameObject (10) then callbacks didnt work

**Comment by af-margot** [comment]
Hi @SnaiperoG3D ,

Thank you for reachint out. 
Please open a ticket to [support@appsflyer.com](mailto:support@appsflyer.com), with logs and code snippets. They will be able to further help you
thank you!
