### ISSUE TITLE
AppsFlyer logo - Nice to fix.

### ISSUE THREAD

**Issue by Antonio-Iliev** [AppsFlyerSDK/appsflyer-unity-plugin#184]
Hello AppsFlyer team,

Thanks for your excellent work with the AppsFluer unity plugin.

If the plugin is installed via Package Manager or via Custom Package but moved to a different folder location the logo disappears.
This is due to the hardcoded image path.
` GUILayout.Box((Texture)AssetDatabase.LoadAssetAtPath("Assets/AppsFlyer/Editor/logo.png", typeof(Texture)), new GUILayoutOption[] { GUILayout.Width(600) });`

It will be nice loading of the image to be dynamic and cached (because the OnInspectorGUI is often invoked).

**Comment by af-margot** [comment]
Hi @Antonio-Iliev,

Thank you for the input !
We will check this and try to add it in a future release :)

**Comment by af-do** [comment]
Hi @Antonio-Iliev,
This was fixed in the 6.9.4 version.

**Comment by Antonio-Iliev** [comment]
Hi @af-do,
Nice! Thank you!
