### ISSUE TITLE
API docs is missing methods

### ISSUE THREAD

**Issue by AdriaandeJongh** [AppsFlyerSDK/appsflyer-unity-plugin#186]
One of those is `sendEvent`, and it appears a few others in the most common API methods are missing, but I didn't list them.

**Comment by af-margot** [comment]
Hi, 

Thank you for reaching out!
You can find the documentation about sendEvent [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/e51841f5ed67eb535f93f86b4077ef7a0e13467a/docs/InAppEvents.md)
Please let us know if you have more questions!
