### ISSUE TITLE
The parameter order of the setHost method is reversed on the iOS platform

### ISSUE THREAD

**Issue by guojunliu** [AppsFlyerSDK/appsflyer-unity-plugin#188]
The parameter order of the setHost method is reversed on the iOS platform

When I call 

```
AppsFlyer.setHost("","appsflyersdk.com");
```

<br>
<br>
<br>

The code call stack is

```
public static void setHost(string hostPrefixName, string hostName)
{

    if (instance != null)
    {
        instance.setHost(hostPrefixName, hostName);
    }
}
```
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/AppsFlyer.cs#L375

<br>
<br>
<br>

```
public void setHost(string host, string hostPrefix)
{
#if !UNITY_EDITOR
    _setHost(host, hostPrefix);
#endif
}
```
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/AppsFlyeriOS.cs#L365

<br>
<br>
<br>

```
const void _setHost (const char* host, const char* hostPrefix) {
    [[AppsFlyerLib shared] setHost:stringFromChar(host) withHostPrefix:stringFromChar(hostPrefix)];
}
```
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyeriOSWrapper.mm#L143

<br>
<br>
<br>

I will get log 

```
[AppsFlyerSDK] [com.apple.main-thread] `host` cannot be `nil` or `empty`
```

<br>
<br>
<br>

The parameter order of the setHost method is reversed on the iOS platform

<img width="666" alt="QQ20221110-115001@2x" src="https://user-images.githubusercontent.com/6713422/200996383-1f88973e-7dbd-4211-ac52-2b791860d52e.png">

**Comment by af-margot** [comment]
Hi @guojunliu,

Thank you for the inupt !
We just released a hotfix for it, [v6.8.5](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/releases/tag/6.8.5).
