### ISSUE TITLE
Handle success and failure when recording in-app events

### ISSUE THREAD

**Issue by koshelevpavel** [AppsFlyerSDK/appsflyer-unity-plugin#19]
Why is there no way in unity SDK to get a callback about success and failure when recording in-app event?

I have little expertise in native plugins. I created it for Android.
https://github.com/koshelevpavel/appsflyer-unity-plugin/commit/dad2f8fb0c3b1d7dabcf1fa245a4653bc22a0a5d

If my commit looks good, I can do it for ios. And create a pull request.

**Comment by wesfieldj** [comment]
@koshelevpavel we added this in the latest version v6.1.0 

Here is a link to the [docs](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Guides.md#request-listeners).
