### ISSUE TITLE
unity ios build error: not found AppsFlyerLib

### ISSUE THREAD

**Issue by liu0fanyi** [AppsFlyerSDK/appsflyer-unity-plugin#192]
full info:
`
Showing Recent Messages
Directory not found for option '-F/Users/mac/Library/Developer/Xcode/DerivedData/Unity-iPhone-abxrudvwhyhjfkbxpigukgbicwug/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppsFlyerLib'
`

`
Showing Recent Messages
Framework not found AppsFlyerLib
`

have tried :

Download and add the required iOS dependencies to the Assets/Plugins/iOS/AppsFlyer folder:
[Download](https://s3.eu-west-1.amazonaws.com/download.appsflyer.com/ios/6.x.x/6.4.x/6.4.4/AF-iOS-SDK-v6.4.4.zip) the iOS SDK as a static library
Unzip the file you downloaded
Drag & drop all the files into the Assets/Plugins/iOS/AppsFlyer folder

not work
any help?
Thanks

**Comment by af-margot** [comment]
Hi,

Thank you for reaching out, please open a ticket to [support@appsflyer.com](mailto:support@appsflyer.com), they will be able to help you !
Thank you.
