### ISSUE TITLE
Returning of old error in package version 6.9.4

### ISSUE THREAD

**Issue by Fixer33** [AppsFlyerSDK/appsflyer-unity-plugin#205]
Hey. 
Just encountered old issue that was discussed earlier: https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/issues/86
I've tried the old solution of changing to 6.2.3 version, but it took no effect.
Problem is in missing com.appsflyer.unity.AppsFlyerAndroidWrapper Java class. I've tried importing .jar library with this class, but unsuccessfully.

**Comment by af-do** [comment]
Hi @Fixer33 and thank you for reaching out to us!
It does not seem to be the same issue as the one you have referenced, the previous issue was related to a mistake in versions numbers in the `AppsFlyerDependencies.xml` file, I can see that the 6.9.4 release has the correct 6.9.4 (Android) dependencies and the versions exist on maven.

In order for us to provide optimal support, please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify:
      - ✅ your AppsFlyer sign-up (account) email
      - ✅ app ID
      - ✅ production steps
      - ✅ logs
      - ✅ code snippets
      - ✅ and any additional relevant information.

**Comment by Fixer33** [comment]
The issue was resolved!
To fix it:
1. Revert all the changes to the state before importing package
2. Install package without using **Dependency Resolver**
