### ISSUE TITLE
The deep link does not work when attempting it multiple times in a row.

### ISSUE THREAD

**Issue by dogukankse** [AppsFlyerSDK/appsflyer-unity-plugin#207]
When I tested deep linking for the first time on an Android device, the onDeepLinking callback was filled with data and I was able to read the deep_link_value without any problems. However, when I tried to run another test 5-10 minutes later, the deep link stopped working and the logcat displayed the following message:

02-23 14:26:44.481 11854 12059 I AppsFlyer_6.9.4: Connection call succeeded:
02-23 14:26:44.484 11854 12030 D AppsFlyer_6.9.4: [DDL] Calling onDeepLinking with:
02-23 14:26:44.484 11854 12030 D AppsFlyer_6.9.4: {"status":"NOT_FOUND"}

The device is registered as a test device to AppsFlyer and the SDK is initialized with debug mode on. Is this a bug, or is this behavior intentional?

**Comment by af-do** [comment]
Hi @dogukankse and thank you for reaching out to us!

In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:
- ✅ your AppsFlyer sign-up (account) email
- ✅ app ID
- ✅ reproduction steps
- ✅ logs
- ✅ code snippets
- ✅ and any additional relevant information.
