### ISSUE TITLE
Apple silicon bundle, DllNotFoundException

### ISSUE THREAD

**Issue by dreamcodestudio** [AppsFlyerSDK/appsflyer-unity-plugin#214]
- Unity editor version: 2020.3.41f1
- AppsFlyer Unity SDK version: 6.8.5 or 6.10.10
- Source you installed the SDK: unitypackage
- Problematic Component: AppsFlyerBundle.bundle

- Platform you are using the Unity editor on: Mac
- Platform you are targeting:Mac
- Scripting Runtime: Mono or IL2CPP

### Issue log:
```
          DllNotFoundException: AppsFlyerBundle
          AppsFlyerSDK.AppsFlyeriOS.setIsDebug (System.Boolean isDebug) (at 
          /Users/dreamcode/Development/unity_projects/vampirem3/Assets/AppsFlyer/AppsFlyeriOS.cs:160)
         AppsFlyerSDK.AppsFlyer.setIsDebug (System.Boolean shouldEnable) (at 
         /Users/dreamcode/Development/unity_projects/vampirem3/Assets/AppsFlyer/AppsFlyer.cs:184)
         _Playflock.Scripts.Game.Analytics.Services.AppsFlyer.AppsFlyerAnalyticsService.Initialize ()
```
### Relevant Code:
```
            var appsFlyerMono = UnityEngine.Object.FindObjectOfType<AppsFlyerListener>();
            if (ReferenceEquals(appsFlyerMono, null))
            {
                var listenerGo = new GameObject("AppsFlyerListener");
                appsFlyerMono = listenerGo.AddComponent<AppsFlyerListener>();
                UnityEngine.Object.DontDestroyOnLoad(listenerGo);
            }
            AppsFlyerSDK.AppsFlyer.setIsDebug(Debug.isDebugBuild);
            AppsFlyerSDK.AppsFlyer.initSDK(_devKey, _appleAppId, appsFlyerMono);
            AppsFlyerSDK.AppsFlyer.setCustomerUserId(playerId);
            AppsFlyerSDK.AppsFlyer.startSDK();
            AppsFlyerAdRevenue.start();
```

**Comment by dreamcodestudio** [comment]
I tried to change Unity `Platform settings` equals `CPU=Any CPU` for supporting Apple silicon architecture, but on runtime get
`EXC_BAD_ACCESS` from com.appsflyer.serial (Thread 4)

**Comment by dreamcodestudio** [comment]
actual on latest 6.10.10 sdk

**Comment by af-do** [comment]
Hi @dreamcodestudio,
Thank you for contacting us and sorry for the long delay, to resolve this issue I would ask you to please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
