### ISSUE TITLE
AppsFlyerLib.h missing method signature

### ISSUE THREAD

**Issue by FilipposKaragiannis** [AppsFlyerSDK/appsflyer-unity-plugin#219]
I am integrating AppsFlyer in unity using Installation without unity-jar-resolver. I downloaded the iOS SDK as a static library and imported the header files. 
Xcode build fails in linking stage with error : "No visible @interface for 'AppsFlyerLib' declares the selector 'setPluginInfoWith:pluginVersion:additionalParams:'"
Going into this AppsFlyerLib.h file I can see that the version of the file is  AppsFlyer iOS SDK 6.4.4 (40) and the signature is missing.
It looks like your DOWNLOAD link takes you to the v.6.4.4 version. 
should I used the header files found here instead ?
https://s3.eu-west-1.amazonaws.com/download.appsflyer.com/ios/6.x.x/6.10.x/6.10.10/AF-iOS-SDK-v6.10.10.zip

![Screenshot 2023-05-10 at 15 06 35](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/assets/57843571/ce1304d9-267b-43f6-8c96-b3c158f2fca5)

**Comment by FilipposKaragiannis** [comment]
Using the header v6.10.1 files from this bucket have another missing header file, `AppsFlyerLib/AppsFlyerCrossPromotionHelper.h` this time.

**Comment by r8nes** [comment]
I have a similar problem with 6.12.2. 

> 'AppsFlyerLib/AppsFlyerCrossPromotionHelper.h' file not found

**Comment by lz2205324544** [comment]
> I have a similar problem with 6.12.2.
> 
> > 'AppsFlyerLib/AppsFlyerCrossPromotionHelper.h' file not found

I have the same issue. Is there a fix yet?
