### ISSUE TITLE
Cannot use AppsFlyer unity plugin v6.12.10 with PurchaseConnector v.1.0.1

### ISSUE THREAD

**Issue by SergeiEfimik** [AppsFlyerSDK/appsflyer-unity-plugin#233]
iOS Build error on Mac:
```
[!] CocoaPods could not find compatible versions for pod “AppsFlyerFramework”:
 In Podfile:
  AppsFlyerFramework (= 6.12.0)
  PurchaseConnector (= 6.10.1) was resolved to 6.10.1, which depends on
   PurchaseConnector/Main (= 6.10.1) was resolved to 6.10.1, which depends on
    AppsFlyerFramework (= 6.10.1)
```

**Comment by af-do** [comment]
Hi @SergeiEfimik,
Thank you for contacting us.
In order for us to provide optimal support please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com) and they will be able to help you further.
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ reproduction steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
