### ISSUE TITLE
Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

### ISSUE THREAD

**Issue by GitterShashank** [AppsFlyerSDK/appsflyer-unity-plugin#238]
Hi

Initially I tried integrating the AppsFlyer plugin into our Unity project via the unity package but for some reason, Unity simply doesn't download the AppsFlyer plugin jars(the SDK, the Wrapper and Install Referrer)) while building the game. Is there any extra setting to be given somewhere like in build.gradle or somewhere so that Unity can download those jars ?

So as the next step I tried building everything manually by downloading the AppsFlyer SDK, the Wrapper and Install Referrer and put it into the Plugins/Android folder. The build went fine but this time around a new runtime error came up when trying to init the SDK on the mobile device :

```
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
at com.appsflyer.internal.platform_extension.PluginInfo.<init>(Unknown Source:2)
at com.appsflyer.unity.AppsFlyerAndroidWrapper.setPluginInfo(AppsFlyerAndroidWrapper.java:418)
at com.appsflyer.unity.AppsFlyerAndroidWrapper.initSDK(AppsFlyerAndroidWrapper.java:50)
at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
```
Any help will be appreciated as we're stuck on integrating the SDK at the moment ! 

Here is the system build config :
Unity 2021.3.8f1
Mac OS 10.14.5
AppsFlyer version 6.12.20 (Also tried 6.12.10 and 6.10.30 with same issues)

**Comment by af-do** [comment]
Hi @GitterShashank,
Thank you for contacting us.
In order for us to provide optimal support please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com) and they will be able to help you further.
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ reproduction steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
