### ISSUE TITLE
[iOS] didResolveDeepLink not being called on cold start

### ISSUE THREAD

**Issue by kshkulev** [AppsFlyerSDK/appsflyer-unity-plugin#239]
didResolveDeepLink is not called at application start if it was killed before. It only works when app was in background. Only iOS platform is affected.

I tried to upgrade plugin to 6.10.30 and used swizzling but the bug still persists.

Unity 2021.3.23f1
AppsFlyerSDK 6.4.0-6.10.30
Xcode 14.2
iOS 15.4.1

**Comment by af-do** [comment]
Hi @kshkulev,
Thank you for contacting us.
In order for us to provide optimal support please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com) and they will be able to help you further.
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ reproduction steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
