### ISSUE TITLE
Doesn't work on iOS

### ISSUE THREAD

**Issue by 0dd431c8** [AppsFlyerSDK/appsflyer-unity-plugin#241]
Was not able to make the unity plugin work on iOS. None of the callbacks (OnDeepLink, conversion success/failure) are not fired when opening the onelink. Here is the [log](https://pastebin.com/BJ7f0WEJ)

**Comment by af-do** [comment]
Hi @0dd431c8,
Thank you for contacting us.
In order for us to provide optimal support please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com) and they will be able to help you further.
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ reproduction steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
