### ISSUE TITLE
Question: Why download the whole repository to get a unity package?

### ISSUE THREAD

**Issue by EcoEditor** [AppsFlyerSDK/appsflyer-unity-plugin#256]
Some plugins allow to download the package without downloading the repo. like: https://github.com/Cysharp/UniTask/releases

if there's no real reason to download the whole repo maybe you can consider that.

**Comment by revenkogrisha** [comment]
I agree that it's strange that they didn't do it, **but...**

Here is the actually **easy solution** for this case without downloading the whole repo: 

1. Just open repo as it is, in the newest stage (just open master branch, it's opened by default)
2. Find _.unitypackage_ file in the repo (it's supposed to be in the root)
3. Click on it
4. Find a small **Download Raw File** button in the top right corner

That's it, you got the package!
In my case the file called _appsflyer-unity-plugin-6.13.10.unitypackage_, if you need any other version, just try navigating through **tags**

<img width="1190" alt="image" src="https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/assets/91753392/a16fa16c-27e2-46b9-b69b-04bbeee82804">
