### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.bun.supplier.IIdentifierListener"

### ISSUE THREAD

**Issue by Leuconoe** [AppsFlyerSDK/appsflyer-unity-plugin#26]
SDK version : unity 5.4.2
Unity Version : 2018.4.14f4

Error when using af-android-sdk:5.4.1
af-android-sdk:5.3.0 is fine.

07-23 13:13:15.427 21578 21643 D AppsFlyer_5.4.1: Initializing AppsFlyer SDK: (v5.4.1.44): com.**********.game.*******
07-23 13:13:15.432 21578 21643 I AppsFlyer_5.4.1: Starting AppsFlyer Tracking: (v5.4.1.44): com.**********.game.*******
07-23 13:13:15.433 21578 21643 I AppsFlyer_5.4.1: Build Number: 44: com.**********.game.*******
07-23 13:13:15.433 21578 21643 D AppsFlyer_5.4.1: Loading properties..: com.**********.game.*******
07-23 13:13:15.434 21578 21643 D AppsFlyer_5.4.1: Done loading properties: true: com.**********.game.*******
07-23 13:13:15.436 21578 21643 I AppsFlyer_5.4.1: appsflyer_backup_rules.xml detected, using AppsFlyer defined backup rules for AppsFlyer SDK data: com.**********.game.*******
07-23 13:13:15.438 21578 21990 I AppsFlyer_5.4.1: onBecameForeground: com.**********.game.*******
07-23 13:13:15.440 21578 21990 I AppsFlyer_5.4.1: Sending first launch for this session!: com.**********.game.*******
07-23 13:13:15.592 21578 21991 I AppsFlyer_5.4.1: sendTrackingWithEvent from activity: android.app.Application: com.**********.game.*******
07-23 13:13:15.594 21578 21991 I AppsFlyer_5.4.1: Trying to fetch GAID..: com.**********.game.*******
07-23 13:13:15.704 21578 21991 I AppsFlyer_5.4.1: ******* sendTrackingWithEvent: Launch: com.**********.game.*******
07-23 13:13:15.722 21578 21991 W AppsFlyer_5.4.1: Exception while collecting facebook's attribution ID. : com.**********.game.*******
07-23 13:13:15.728 21578 21991 I AppsFlyer_5.4.1: IMEI was not collected.: com.**********.game.*******
07-23 13:13:15.733 21578 21991 I AppsFlyer_5.4.1: Android ID was not collected.: com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.appsflyer.oaid.OaidClient$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/supplier/IIdentifierListener;: com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.util.Map com.appsflyer.AppsFlyerLibCore.?(com.appsflyer.AFEvent) (:50600): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AppsFlyerLibCore.Ι(com.appsflyer.AFEvent) (:1603): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AppsFlyerLibCore.ι(com.appsflyer.AppsFlyerLibCore, com.appsflyer.AFEvent) (:99): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AppsFlyerLibCore$e.run() (:3307): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:428): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.FutureTask.run() (FutureTask.java:237): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:272): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AFExecutor$1$1.run() (:31): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.lang.Thread.run() (Thread.java:761): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bun.supplier.IIdentifierListener" on path: DexPathList[[zip file "/data/app/com.**********.game.*******-1/base.apk"],nativeLibraryDirectories=[/data/app/com.********.game.********-1/lib/arm, /data/app/com.********.game.********-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]: com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.util.Map com.appsflyer.AppsFlyerLibCore.?(com.appsflyer.AFEvent) (:50600): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AppsFlyerLibCore.Ι(com.appsflyer.AFEvent) (:1603): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AppsFlyerLibCore.ι(com.appsflyer.AppsFlyerLibCore, com.appsflyer.AFEvent) (:99): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AppsFlyerLibCore$e.run() (:3307): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:428): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.FutureTask.run() (FutureTask.java:237): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:272): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void com.appsflyer.AFExecutor$1$1.run() (:31): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     :   at void java.lang.Thread.run() (Thread.java:761): com.**********.game.*******
07-23 13:13:15.741 21578 21991 I art     : : com.**********.game.*******

**Comment by harr999y** [comment]
Same question, any ideas?

**Comment by cberkeleyHutch** [comment]
Same issue using Unity SDK v6.0.3 and Unity 2018.4 LTS

**Comment by lix-iaoming** [comment]
Same question, any ideas?

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!
