### ISSUE TITLE
Cannot build with xCode 15.3

### ISSUE THREAD

**Issue by IoannisFMG** [AppsFlyerSDK/appsflyer-unity-plugin#263]
Hello!

I just updated xCode to 15.3 and there seems to be an ISO C99 issue with the `AppsFlyer+AppController.m`file.
The attached image is a screenshot from xCode 15.2 where the issue 

> Type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int

 marked as a warning has now become an error. The fix seems to be just a simple cast, but still the build fails.

I am using an older version of the SDK, but I have checked the repo and the code for [the specific method](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/b820d926d5af3b5d5813bd5e6981037dee150e0e/Assets/AppsFlyer/Plugins/iOS/AppsFlyer%2BAppController.m#L144) hasn't changed yet. Could you please take a look at it?

Cheers!

<img width="889" alt="Screenshot 2024-03-06 at 13 44 22" src="https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/assets/70578756/a536b94f-d554-4a17-860a-31620ee68776">

**Comment by victor-kallai** [comment]
I have the same problem, waiting for a fix.

**Comment by juaprebo** [comment]
I have got the same issue.

**Comment by StuWebstMW** [comment]
Also seeing this.

**Comment by silver6628** [comment]
Please fix it as soon as possible. App updates are not possible.

**Comment by champie** [comment]
As a temporary workaround, seems that accepting Xcode's suggested fix for that error allows you to build at least. To save doing that every build you can make the change to the package version in /Library/PackageCache/appsflyer-unity-plugin@xxxxxxxxxx/AppsFlyer+AppController.m (line 144 in the version I have), just add `int` before `(UIBackgroundFetchResult)`, i.e.;

`        return ((BOOL(*)(id, SEL, UIApplication*, NSDictionary*, int(UIBackgroundFetchResult)))__original_didReceiveRemoteNotification_Imp)(self, _cmd, application, userInfo, nil);
`

**Comment by Duloinc** [comment]
Having the same issue! 

The fix above works!

**Comment by st21a1** [comment]
The previous method definition is BOOL __swizzled_didReceiveRemoteNotification(id self, SEL _cmd, UIApplication* application, NSDictionary* userInfo, void (^UIBackgroundFetchResult)(void)). Therefore, I modified it to:
return ((BOOL()(id, SEL, UIApplication, NSDictionary*, void (^UIBackgroundFetchResult)(void)))__original_didReceiveRemoteNotification_Imp)(self, _cmd, application, userInfo, nil);
It seems to be fine.

**Comment by jedai7** [comment]
when sdk will be updated?

**Comment by serzit** [comment]
same issue, need fix ASAP

**Comment by Decavoid** [comment]
> same issue, need fix ASAP

I you need a fix ASAP, downgrade Xcode to 15.2.

**Comment by NudeNULL** [comment]
Have the same issue, fix the error please...

**Comment by Gnts** [comment]
Downgraded to xcode 15.2 to avoid the suggested workaround, waiting for a fix 🙏

**Comment by TDS-Arikaton** [comment]
+1

**Comment by gsteinkirch-bytro** [comment]
It seems this issue has been fixed at the Appsflyer's ios SDK (https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-release-notes)

Could we please have the this fix on unity's SDK as well?

**Comment by andy-block** [comment]
+1 waiting for a resolution on this...

**Comment by ersagunkuruca** [comment]
Is this resolved with the latest release?

**Comment by af-vero** [comment]
Hi, we will release the fix with a new version

**Comment by IoannisFMG** [comment]
It's obvious that it will be fixed in a new version. We'd like to have a timeframe though, please.

**Comment by af-vero** [comment]
till the end of the week

**Comment by af-vero** [comment]
released in version 6.14.0
