### ISSUE TITLE
How to execute the continueUserActivity function in UnityAppController?

### ISSUE THREAD

**Issue by AimeWang** [AppsFlyerSDK/appsflyer-unity-plugin#266]
What data does the continueUserActivity function implemented by AppsFlyer primarily collect from users? 
I'm currently trying to use universal links on iOS, but I noticed that the continueUserActivity function in UnityAppController is not being executed. 
Will adding [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler]; in AppsFlyerAppController impact the AppsFlyer tracking data?

**Comment by pazlavi** [comment]
👋 Hi @AimeWang  and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
