### ISSUE TITLE
Empty game object name

### ISSUE THREAD

**Issue by IgorGalimski** [AppsFlyerSDK/appsflyer-unity-plugin#27]
Hi! Our team faced an issue - an empty game object name. Here is the fix
`    
const void _validateAndSendInAppPurchase (const char* productIdentifier, const char* price, const char* currency, const char* tranactionId, const char* additionalParameters, const char* objectName) {

        validateObjectName = stringFromChar(objectName);

        [[AppsFlyerTracker sharedTracker]
         validateAndTrackInAppPurchase:stringFromChar(productIdentifier)
         price:stringFromChar(price)
         currency:stringFromChar(currency)
         transactionId:stringFromChar(tranactionId)
         additionalParameters:dictionaryFromJson(additionalParameters)
         success:^(NSDictionary *result){
                 unityCallBack(validateObjectName, VALIDATE_CALLBACK, stringFromdictionary(result));
         } failure:^(NSError *error, id response) {
                 unityCallBack(validateObjectName, VALIDATE_ERROR_CALLBACK, error ? [[error localizedDescription] UTF8String] : "error");
         }];
    }

const void _generateUserInviteLink (const char* parameters, const char* objectName) {

    	validateObjectName = stringFromChar(objectName);	

        [AppsFlyerShareInviteHelper generateInviteUrlWithLinkGenerator:^AppsFlyerLinkGenerator * _Nonnull(AppsFlyerLinkGenerator * _Nonnull generator) {
            return generatorFromDictionary(dictionaryFromJson(parameters), generator);
        } completionHandler:^(NSURL * _Nullable url) {
            unityCallBack(validateObjectName, GENERATE_LINK_CALLBACK, [url.absoluteString UTF8String]);
        }];
    }`

Instead of
`const void _attributeAndOpenStore (const char* appID, const char* campaign, const char* parameters, const char* objectName) {
        [AppsFlyerCrossPromotionHelper
         trackAndOpenStore:stringFromChar(appID)
         campaign:stringFromChar(campaign)
         paramters:dictionaryFromJson(parameters)
         openStore:^(NSURLSession * _Nonnull urlSession, NSURL * _Nonnull clickURL) {
             unityCallBack(stringFromChar(objectName), OPEN_STORE_LINK_CALLBACK, [clickURL.absoluteString UTF8String]);
             
         }];
    }
    
const void _generateUserInviteLink (const char* parameters, const char* objectName) {
        [AppsFlyerShareInviteHelper generateInviteUrlWithLinkGenerator:^AppsFlyerLinkGenerator * _Nonnull(AppsFlyerLinkGenerator * _Nonnull generator) {
            return generatorFromDictionary(dictionaryFromJson(parameters), generator);
        } completionHandler:^(NSURL * _Nullable url) {
            unityCallBack(stringFromChar(objectName), GENERATE_LINK_CALLBACK, [url.absoluteString UTF8String]);
        }];
    }`

**Comment by wesfieldj** [comment]
@IgorGalimski Thanks for reporting. We will fix this in the next release.

**Comment by jfperusse-bhvr** [comment]
Confirming we have the same issue with Unity SDK 5.4.2 and the invite link generation does not work on iOS.

**Comment by wesfieldj** [comment]
The issue was fixed in v6.0.3 #41
