### ISSUE TITLE
New Unity plugin with the privacy manifest?

### ISSUE THREAD

**Issue by silviosav-SEGA-HARDlight** [AppsFlyerSDK/appsflyer-unity-plugin#271]
Hello,

I noticed the [iOS SDK](https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-release-notes) has been released not long ago and it's including the privacy manifest which is a [requirement](https://developer.apple.com/news/?id=3d8a9yyh) Apple is going to enforce from the 1st of May.

So when is the Unity plugin going to be released?

Thanks,
Silvio

**Comment by af-vero** [comment]
released today :)
