### ISSUE TITLE
AppsFlyer package json version is not matching 6.14.0 release

### ISSUE THREAD

**Issue by silviosav-SEGA-HARDlight** [AppsFlyerSDK/appsflyer-unity-plugin#274]
Hello,

Thanks for the Unity plugin release. 

I just noticed that in the Unity/Assets/AppsFlyer/package.json the version is not matching the 6.14.0 release which is instead present in the Unity/Assets/AppsFlyer/AppsFlyer.cs script.

I thought it was worth reporting it.

Bests,
Silvio

**Comment by af-vero** [comment]
Thanks for your note
