### ISSUE TITLE
App crashes with restorationHandler

### ISSUE THREAD

**Issue by IgorGalimski** [AppsFlyerSDK/appsflyer-unity-plugin#28]
Hi! We have an issue in a game - we use Appboy and Appsflyer. We use merged controller, and after opening the game from appsflyer generated link we got a crash
<img width="1920" alt="Screen Shot 2020-07-24 at 11 36 03" src="https://user-images.githubusercontent.com/19680568/88380584-7c7fad80-cdad-11ea-81a3-1d026a4dd6ec.png">

We didn't receive the crash on previous versions AF SDK, because we didn't have super call
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/commit/0691a13e783872afba7d17b0cf97377aa19dd29d#diff-634bfcf211bafb405b063f342663175f

Could you please check - is it safe to remove this call? What is it for?

**Comment by IgorGalimski** [comment]
Up

**Comment by wesfieldj** [comment]
@IgorGalimski the super call was added to solve conflicts with third party SDKs such as firebase. 

It is safe to remove the super call. Its only purpose is to prevent conflicts.  

Can you please provide AppsFlyer support (support@appsflyer.com) with more details so we can help prevent such an issue in the future. 

Thanks for reporting.

**Comment by IgorGalimski** [comment]
Hi! @wesfieldj Thanks for the reply! Now it's more understandable for me.
