### ISSUE TITLE
Wrong app open data on the first launch

### ISSUE THREAD

**Issue by IgorGalimski** [AppsFlyerSDK/appsflyer-unity-plugin#29]
Hi! After updating to SDK version 5.4.1 from 4.18.0 we faced an issue - for the first launch we receive open app data
`{
  "install_time": "2020-07-27 14:06:22.830",
  "media_source": "restricted",
  "agency": null,
  "retargeting_conversion_type": "none",
  "af_siteid": null,
  "af_status": "Non-organic",
  "is_first_launch": true,
  "af_sub1": null,
  "af_sub5": null,
  "click_time": null,
  "af_sub4": null,
  "af_sub3": null,
  "af_sub2": null,
  "http_referrer": null,
  "campaign": null,
  "af_channel": null,
  "campaign_id": null
}`

After reinstall
`{
  "redirect_response_data": null,
  "adgroup_id": null,
  "engmnt_source": null,
  "retargeting_conversion_type": "none",
  "orig_cost": "0.0",
  "is_first_launch": true,
  "af_click_lookback": "7d",
  "af_cpi": null,
  "iscache": true,
  "click_time": "2020-07-27 13:03:03.887",
  "is_branded_link": null,
  "match_type": "fingerprinting",
  "af_referrer_uid": "1595850286616-819367868486402837",
  "adset": null,
  "campaign_id": null,
  "shortlink": "b9c6fbdc",
  "install_time": "2020-07-27 13:03:13.544",
  "media_source": "af_app_invites",
  "AppInvitePublicPlayeId": "5c6c415e3b00b90bfc778c2f",
  "agency": null,
  "af_siteid": "out_game",
  "af_status": "Non-organic",
  "af_sub1": null,
  "cost_cents_USD": "0",
  "af_sub5": null,
  "af_sub4": null,
  "af_sub3": null,
  "af_sub2": null,
  "adset_id": null,
  "esp_name": null,
  "campaign": "None",
  "http_referrer": null,
  "is_universal_link": null,
  "adgroup": null
} `

In the previous version, we received the second JSON on the first request. What was changed?

Thanks!

**Comment by IgorGalimski** [comment]
Up

**Comment by wesfieldj** [comment]
@IgorGalimski We made changes to the conversion data API in SDK version 5.0.0.

These changes can be seen [here](https://support.appsflyer.com/hc/en-us/articles/115001256006#android-v500-release-notes).
