### ISSUE TITLE
Tests meta file

### ISSUE THREAD

**Issue by NordlightPer** [AppsFlyerSDK/appsflyer-unity-plugin#294]
After upgrading from 6.14.0 to 6.14.4 we get this warning in Unity

`A meta data file (.meta) exists but its folder 'Packages/appsflyer-unity-plugin/Tests' can't be found, and has been created. Empty directories cannot be stored in version control, so it's assumed that the meta data file is for an empty directory in version control. When moving or deleting folders outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
`

It's not the end of the world but I want to keep the project free from warnings

**Comment by Tommigun1980** [comment]
Could this be fixed as this marks our builds as unstable?
