### ISSUE TITLE
'AppsFlyerLib.h' file not found

### ISSUE THREAD

**Issue by khrchvnkv** [AppsFlyerSDK/appsflyer-unity-plugin#297]
Unity 2022.3.36
AppsFlyer 6.14.5
XCode 15.2

When executing the Archive command, an error occurs "'AppsFlyerLib.h' file not found" in the AppsFlyerAttribution.h file. The XCode project does not really have this file, but I integrated the full unitypackage. Before that, there was AppsFlyer version 6.8.2 and there was exactly the same error. After trying to update, the error did not disappear and I do not understand how to solve it

Thanks in advance!

**Comment by vantos3001** [comment]
same error

**Comment by khrchvnkv** [comment]
@vantos3001 Are you sure you are using .xcworkspace? My problem was that I was trying to archive .xcodeproj

**Comment by vantos3001** [comment]
these settings in external manager.
![image](https://github.com/user-attachments/assets/55bc0864-c125-4889-b56f-23b05cd1a8dc)
