### ISSUE TITLE
Please do not use Assets/Plugins/Android

### ISSUE THREAD

**Issue by stopiccot** [AppsFlyerSDK/appsflyer-unity-plugin#3]
Use Assets/Plugins/AppsFlyer/Android folder instead. So all AppsFlyer related files reside in single folder. Unity supports nested plugins folders since 5.0 and I guess there is no need to support 4.x anymore. See https://github.com/AppsFlyerSDK/Unity/pull/51

**Comment by stopiccot** [comment]
Instead of single `Assets/Plugins/AppsFlyer` folder with all files AppsFlyerUnityPlugin_v5.2.0_rc1.unitypackage populates `Assets/AppsFlyer`, `Assets/Plugins/Android`, and `Assets/Plugins/iOS/AppsFlyer` folders. It's really bad idea to do that in 2020.

**Comment by MartinGonzalez** [comment]
A guess a better structure would be
Assets/AppsFlyer/Plugins instead of Assets/Plugins/PLATFORM/Appsflyer
Its clean, and if we want to delete it we only have to erase 1 folder.

**Comment by MahdiGhiasi** [comment]
I agree with @MartinGonzalez , Microsoft's AppCenter uses the same folder structure as well. (so you need to delete 1 folder when you want to delete)
