### ISSUE TITLE
AppTrackingTransparency pop-up never shows up

### ISSUE THREAD

**Issue by Cptweirdo** [AppsFlyerSDK/appsflyer-unity-plugin#31]
After following the readme provided, we get the following error log on trying to invoke the iOS ATT confirmation pop-up:

`[DEBUG] AppsFlyer: [SKAd] Timeout exceded. sk_exp = 0.000000`

This c# code gets executed on Unity's side:
`
AppsFlyer.initSDK(IOSAppsFlyerKkey, IOSAppId, this);
if (new Version(Device.systemVersion) .CompareTo(new Version("14.0")) >= 0)
{
    AppsFlyeriOS.waitForAdvertisingIdentifierWithTimeoutInterval(60);
}
AppsFlyer.startSDK();
`

This is the modified AppsFlyerAppController.mm "didFinishLaunching" snippet:
`
- (void)didFinishLaunching:(NSNotification*)notification {
    if (@available(iOS 14, *)) {
      [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status){
      }];
    }
    NSLog(@"got didFinishLaunching = %@",notification.userInfo);
    if (notification.userInfo[@"url"]) {
        [self onOpenURL:notification];
    }
}
`

**Comment by wesfieldj** [comment]
@Cptweirdo

**Comment by wesfieldj** [comment]
@Cptweirdo 

Have you added the `NSUserTrackingUsageDescription` flag to your info.plist?

Also, make sure to uninstall the app between tests. 

The pop up should appear if all the requirements [here](https://developer.apple.com/documentation/apptrackingtransparency) are met.

**Comment by Cptweirdo** [comment]
We have the following lines in our plist:

`    <key>NSUserTrackingUsageDescription</key>
    <string>To improve user experience we'd like to access Tracking Usage Description</string>`

**Comment by wesfieldj** [comment]
@Cptweirdo 

1. Can you confirm you are using a iOS 14 device?
2. Can you confirm in Settings > Privacy > Tracking > Allow Apps to Request to Track this is turned on?

**Comment by Cptweirdo** [comment]
Yes on both questions. One strange thing: I don't see our app in "Allow Apps to Track" settings. That is strange given the plist flag is there.

![photo_2020-08-13_14-28-14](https://user-images.githubusercontent.com/1552257/90139062-254f7600-dd78-11ea-85ea-2bff98a148fb.jpg)
![photo_2020-08-12_16-34-46](https://user-images.githubusercontent.com/1552257/90139146-41531780-dd78-11ea-8906-15a6c3c861fe.jpg)

**Comment by MagicMiikka** [comment]
What XCode are you using?

My investigation on a different issue lead me to notice that this Info.plist entry does not translate into "Privacy - Tracking Description" on XCode 11.6. On Xcode 12 Beta, this translated correctly in the Info.plist but I did not get a prompt on my issue.

**Comment by myrik** [comment]
I ran into something like this yesterday and it seems to be because AppsFlyerAppController isn't actually being used (I don't see any of the NSLogs in my console). 

We also have Swrve integrated in our app and adding the call to requestTrackingAuthorizationWithCompletionHandler in SwrveUnityAppControllerSub fixed it for us. I haven't dug too deep into this yet, but perhaps another class is overriding UnityAppController for you?

**Comment by iyakov** [comment]
Hello @wesfieldj , 
Is it correct that AppsFlyerSdk will not call requestTrackingAuthorizationWithCompletionHandler to ask for permissions, and it is a developer responsibility to make this call explicitly?
Thanks in advance

**Comment by hesham-akmal** [comment]
Spent a million hours to figure out why the DIALOG IS NEVER SHOWN. AppsFlyerAppController is NOT used in my case! 
I added 
if (@available(iOS 14, *)) {
        printf("APPSFLYER available(iOS 14, *)");
                [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
                    NSLog(@"status : %lu",(unsigned long) status);
                    printf("APPSFLYER REQUESTING TRACKING TEST AA");
                }
                ];
            }
            
in the _startSDK of AppsFlyeriOSWrapper.mm and it finally works

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. 
Please reopen if you still encounter this issue :) 

Thank you!

**Comment by Goncharuk-Nikita** [comment]
Hello, I just copy some unanswered questions on this topic.

1. Is it correct that AppsFlyerSdk will not call requestTrackingAuthorizationWithCompletionHandler to ask for permissions, and it is a developer's responsibility to make this call explicitly?

2. If yes, Should I call it before or after initSDK or startSDK? Should I wait for a permission callback and then startSDK? (In AppsFlyer Unity SDK)
