### ISSUE TITLE
Recieving Error in 6.0.1_beta branch

### ISSUE THREAD

**Issue by jollymonkey** [AppsFlyerSDK/appsflyer-unity-plugin#32]
Unity Editor Version: 2018.3.9f1
Platform: Android

After updating to the 6.0.1_beta (using EDM4U) branch in one of our titles i am seeing the following error:

08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: Exception in sendRequestToServer. 
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: java.io.FileNotFoundException: https://conversions.appsflyer.com/api/v5.4/androidevent?app_id=**com.k**&buildnumber=5.4.1
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.safedk.android.internal.partials.AppsFlyerNetworkBridge.httpUrlConnectionGetResponseCode(AppsFlyerSourceFile:141)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.appsflyer.AppsFlyerLibCore.ι(:3005)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.appsflyer.AppsFlyerLibCore.ı(:50928)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.appsflyer.AppsFlyerLibCore$a.run(:3375)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at com.appsflyer.AFExecutor$1$1.run(:31)
08-14 10:25:34.052 11867 12601 E AppsFlyer_5.4.1: 	at java.lang.Thread.run(Thread.java:764)
08-14 10:25:34.053 11867 12601 I AppsFlyer_5.4.1: failed to send requeset to server. https://conversions.appsflyer.com/api/v5.4/androidevent?app_id=**com.k**&buildnumber=5.4.1

**Comment by wesfieldj** [comment]
Hi @jollymonkey 

Thank you for reporting this issue.

We were not able to reproduce this.

Can you please open a ticket to AppsFlyer support by emailing support@appsflyer.com.
Please include a link to this issue, account details, and any other relevant information.
AppsFlyer support will help you get this issue resolved.

Thank you

**Comment by jollymonkey** [comment]
Thanks will do.
