### ISSUE TITLE
AppsFlyerObjectScript needs to call DontDestroyOnLoad?

### ISSUE THREAD

**Issue by nguyentrong101094** [AppsFlyerSDK/appsflyer-unity-plugin#33]
In the v5 integration guide https://support.appsflyer.com/hc/en-us/articles/360007314277-Unity-plugin-V5-integration-guide-for-developers#integration-32-initialize-the-plugin I notice this line "Note: Make sure not to call destroy on the game object."
So the game object with the script AppsFlyerObjectScript needs to persist through every scene in the game, right? But in the example code, I don't see the function DontDestroyOnLoad() gets called. This will leads to the object with this script getting destroyed when Unity load a new scene.

**Comment by wesfieldj** [comment]
@nguyentrong101094 

Thanks for the input. We will look into adding this to the next release and docs.

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!
