### ISSUE TITLE
Notification Center tracker

### ISSUE THREAD

**Issue by IgorGalimski** [AppsFlyerSDK/appsflyer-unity-plugin#40]
Hi! I started to use userNotificationCenter
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623117-application?language=objc
And stopped to received callback here
<img width="881" alt="Screen Shot 2020-09-04 at 17 38 44" src="https://user-images.githubusercontent.com/19680568/92251438-88df4600-eed5-11ea-8f4b-dff4ca23bff5.png">

Could you please check - can I use new callback? It calls with local and remote pushes. Will everything be ok?
Thanks!

**Comment by wesfieldj** [comment]
@IgorGalimski checking.

Thanks for opening this issue.

**Comment by IgorGalimski** [comment]
Hi, @wesfieldj !
Could you please results of the checking?
Thanks!

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!
