### ISSUE TITLE
using Proguard with AF in unity fails?

### ISSUE THREAD

**Issue by toom1984** [AppsFlyerSDK/appsflyer-unity-plugin#52]
Warning: Exception while processing task java.io.IOException: proguard.ParseException: Expecting class member name before 'ι' in line 27 of file 'C:\Users\etg25\.gradle\caches\transforms-1\files-1.1\com.appsflyer.af-android-sdk-6.1.0.aar\f7dc66a21b9e5d977b2094dc7c353f6c\proguard.txt'

Anyone know how to fix this?

**Comment by af-fess** [comment]
Are you using Dexguard v9?

**Comment by toom1984** [comment]
This is using the proguard minify option for unity build in player settings.

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!
