### ISSUE TITLE
AppsFlyer 6.1.3 manifest conflicts with Vungle network

### ISSUE THREAD

**Issue by NudeNULL** [AppsFlyerSDK/appsflyer-unity-plugin#54]
This manifest is created dynamically during the build, so I have no control other that. Is there a way to fix it on your side?

Manifest merger failed : Attribute application@fullBackupContent value=(@xml/vungle_backup_rule) from [com.vungle:publisher-sdk-android:6.8.0] AndroidManifest.xml:20:9-60
	is also present at [com.appsflyer:af-android-sdk:6.1.3] AndroidManifest.xml:16:18-73 value=(@xml/appsflyer_backup_rules).
	Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:5:3-126 to override.

**Comment by AntKarlov** [comment]
Same problem with AppsFlyer and Applovin MAX.

**Comment by NudeNULL** [comment]
Thats what I am talking about, I also use MAX SDK, and there is Vungle mediation network.

For now I found a solution, to overwrite the rules used by AppsFlyer and Vungle with my file. where I merge manually both sides rules.

For that I had to find the manifests downloaded when building the project (somewhere in UserName/.gradle folder), and merged the content of both files from Vungle and ApssFlyer into my file that is stored locally within the project, and in my manifest I set the build to ignore any Attribute application@fullBackupContent, and right after that I specified my file to be used as a rule.

I hope it will work in runtime, not sure right now because other errors poped up, maybe still related to Appslyer...

**Comment by AntKarlov** [comment]
We have resolved this issue by following steps as this thread:
https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9

By adding into AndroidManifest:
```
<application android:fullBackupContent="@xml/appsflyer_backup_rules" tools:replace="android:fullBackupContent" .. >
```

**Comment by af-vs** [comment]
Hi everyone!

Please refer to https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9#issuecomment-760150089 with all the details. It is very important to do the manual merging or disable the Auto Backup feature completely. Otherwise, you can harm some SDK behavior.

If you have any questions, please continue in the linked thread to have a discussion in one place.

Thank you!

**Comment by masoudarvishian** [comment]
> We have resolved this issue by following steps as this thread:
> [AppsFlyerSDK/appsflyer-android-sdk#9](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9)
> 
> By adding into AndroidManifest:
> 
> ```
> <manifest xmlns:tools="http://schemas.android.com/tools" .. >
> <application android:fullBackupContent="@xml/appsflyer_backup_rules" tools:replace="android:fullBackupContent" .. >
> ```

Thank you, solved my problem.
