### ISSUE TITLE
UnityEngine.iOS.NotificationServices.deviceToken is deprecated on Unity 2019.4+

### ISSUE THREAD

**Issue by moritz-wundke** [AppsFlyerSDK/appsflyer-unity-plugin#56]
We use [uninstall tracking ](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Guides.md#track-app-uninstalls)as as such we have to provide you with the device token.

From Unity 2019.4 the following has been deprecated and won't return a valid token: `UnityEngine.iOS.NotificationServices.deviceToken`

We also use Firebase for our push notifications, could we just provide the firebase token using ` AppsFlyeriOS.registerUninstall`?

**Comment by wesfieldj** [comment]
@moritz-wundke Thanks for reporting!

We will investigate and get back to you soon.

Regarding providing the firebase token, this will not work since we only support APN token for uninstall measurement.

**Comment by moritz-wundke** [comment]
Here is how you should request the token in builds using Unity 2019.4+ versions:

First of all you have to add the `Unity Mobile Notifications package` to your Unity project using the Unity Package Manager. Once installed you can request the token like in the following snippet:

```c#
IEnumerator RequestUninstallToken()
{
    const AuthorizationOption AUTHORIZATION_OPTION = AuthorizationOption.Alert | AuthorizationOption.Badge;
    using (var req = new AuthorizationRequest(AUTHORIZATION_OPTION, true))
    {
        while (!req.IsFinished)
        {
            yield return null;
        }
        
        if (req.Granted && req.DeviceToken.IsNotNullNorEmpty())
        {
            AppsFlyeriOS.registerUninstall(Encoding.UTF8.GetBytes(req.DeviceToken));
        }
    }
}
```

If token is empty you might have to enable the request and for push notifications in packages project settings.
![image](https://user-images.githubusercontent.com/414077/106752168-6c813a00-662a-11eb-8656-aa0757869b3d.png)

**Comment by wesfieldj** [comment]
@moritz-wundke thanks for the suggestion. 

We updated the [docs](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Guides.md#track-app-uninstalls-ios) accordingly.
