### ISSUE TITLE
[Question] Ask for IDFA permission

### ISSUE THREAD

**Issue by MartinGonzalez** [AppsFlyerSDK/appsflyer-unity-plugin#58]
Hi, I have one question about showing the pop up that allow user to give or not permission to the app to track idfa.

Is appsflyer giving a method to call it or we should call it by ourself?

Thanks

**Comment by wesfieldj** [comment]
Hi @MartinGonzalez

AppsFlyer does not provice a method to show the pop up. This needs to be managed by the app.

**Comment by MartinGonzalez** [comment]
Thanks!
