### ISSUE TITLE
Support UPM package

### ISSUE THREAD

**Issue by MartinGonzalez** [AppsFlyerSDK/appsflyer-unity-plugin#6]
I guess it's time to start delivering the plugin through Unity Package Manager. This would be really useful/easy for devs.

**Comment by af-fess** [comment]
@MartinGonzalez yes, in our plans, thanks

**Comment by MartinGonzalez** [comment]
Thats great!

**Comment by stopiccot** [comment]
Yep, any news on this one?

**Comment by ErnSur** [comment]
Also waiting for it 😬

**Comment by jlubeck** [comment]
Just stating another interested user!

**Comment by stopiccot** [comment]
@af-fess Any news on this?

**Comment by lsw1164** [comment]
@af-fess Any news on this?
