### ISSUE TITLE
The onConversionDataSuccess method marks all installations from Facebook Ads as "Organic" (iOS)

### ISSUE THREAD

**Issue by ohchillman** [AppsFlyerSDK/appsflyer-unity-plugin#68]
Hello!
There was a problem that all users who installed the application after clicking on Facebook ads are marked as Organic by the onConversionDataSuccess method. Everything is working correctly in the dashboard, I can see all Non-Organic installs correctly. The problem is only at the SDK level.

Also if I use SDK Integration test in dashboard everything works correctly and SDK sends Non-organic install.

I am using Unity 2019.4.17f1, AppsFlyer SDK version is 6.2.3.

Tell me, please, what could be the matter? Thank you in advance!

**Comment by af-margot** [comment]
Hi @ohchillman , 

Thank you for reaching out!
As the tests are working, I'm not sure what could be the issue. 
Please contact our [support](support@appsflyer.com), with all your details (app id, logs if possible, examples of the problematic cases..), they will be able to better help you!
