### ISSUE TITLE
Crashlytics reporting AFSDK-related crashes since update to 6.2.3

### ISSUE THREAD

**Issue by ATA-Temptress** [AppsFlyerSDK/appsflyer-unity-plugin#71]
Hi there,

It seems that after updating our application to version 6.2.3 of the plugin, we've started receiving an uptick in `EXC_BAD_ACCESS KERN_INVALID_ADDRESS` crashes. Example crash log, as reported on Firebase, is as follows:

```
0x10320b7d4 CrashReporting::CrashReporter::SendReport(CrashReporting::CrashReport&) + 935 (UnityWebRequestProto.h:935)
 0x10320aec4 CrashReporting::CrashReporter::HandleLog(core::basic_string<char, core::StringStorageDefault<char> > const&, core::basic_string<char, core::StringStorageDefault<char> > const&, core::basic_string<char, core::StringStorageDefault<char> > const&, LogType) + 324 (CrashReporter.cpp:324)
0x10320aba0 CrashReporting::CrashReporter::OnLogCallbackStatic(DebugStringToFileData const&, LogType, bool) + 191 (String.h:191)
0x10364f9c8 CallbackArray3<DebugStringToFileData const&, LogType, bool>::Invoke(DebugStringToFileData const&, LogType, bool) + 405 (CallbackArray.h:405)
0x10364f658 DebugStringToFilePostprocessedStacktrace(DebugStringToFileData const&) + 1006 (LogAssert.cpp:1006)
0x1034cbc64 Scripting::LogException(ScriptingExceptionPtr, int, char const*, bool) + 819 (Scripting.cpp:819)
0x1057486f4 -[AFSDKEvent sign].cold.1 + 4415653620
0x105748604 -[AFSDKEvent sign].cold.1 + 4415653380
0x10598f840 -[AFSDKEvent sign].cold.1 + 4418041920
0x102ebdca8 RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017_RuntimeObject_RuntimeObject(void (*)(), MethodInfo const*, void*, void**) + 68625 (Il2CppInvokerTable.cpp:68625)
0x103aa4a6c il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 584 (Runtime.cpp:584)
0x103aa53a4 il2cpp::vm::Runtime::CallUnhandledExceptionDelegate(Il2CppDomain*, Il2CppDelegate*, Il2CppException*) + 521 (Runtime.cpp:521)
0x103aa5330 il2cpp::vm::Runtime::UnhandledException(Il2CppException*) + 677 (Runtime.cpp:677)
 0x103a73ebc il2cpp::icalls::mscorlib::System::Threading::ThreadStart(void*) + 169 (Thread.cpp:169)
0x103a7c8f8 il2cpp::os::Thread::RunWrapper(void*) + 174 (Thread.cpp:174)
0x103a7eab4 il2cpp::os::ThreadImpl::ThreadStartWrapper(void*) + 106 (ThreadImpl.cpp:106)
 0x1d5bbbcb0 _pthread_start + 320
0x1d5bc4778 thread_start + 8
```

I'm unsure as to what would be causing this. We did upgrade from an older (<6.0) version of the SDK, and I followed the SDK initialization/migration instructions to the best of my ability. For the time being, we've decided to release a new version of the app with the SDK rolled back pending resolution of this issue.

As far as I can tell, the only difference is that we call the `initSDK(devKey, appID)` function statically from a manager class, without having an actual `gameObject` with the AppsFlyer script attached, but I'm not sure that that would cause this. Any insight would be appreciated.

**Comment by af-margot** [comment]
Hi @ATA-Temptress, 

Thank you for reaching out! 
I'm not sure what is causing the issue. But let's check a few points. 
Are you able to reproduce the issue? Any chance to get a stack trace from Xcode? 
From which version did you update?

About the migration, there is still a game Object. It can either be your old game Object updated, or the AppsFlyerObject.prefab from the new AppsFlyer plugin.  When you did the migration, at the step [**Init new Plugin**](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/MigrationGuide.md#-init-new-plugin), which option did you chose? 
Could you also check that the iOS AppsFlyer SDK version used is 6.2.3. You can check it in the podfile, after exporting the project to XCode.

**Comment by ATA-Temptress** [comment]
Hi @af-margot,

> Are you able to reproduce the issue? Any chance to get a stack trace from Xcode?
It seems that this only comes up in Production. I have not had the chance to verify this locally.

> From which version did you update?
I believe we were on 4.21.1 previously. 

> When you did the migration, at the step [**Init new Plugin**](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/MigrationGuide.md#-init-new-plugin), which option did you chose?
We chose the option that does not involve the prefab. We have an `AnalyticsManager` class that handles all of the AppsFlyer functionality. The game object itself does not contain the `AppsFlyer` MonoBehaviour as a component, but instead invokes `initSDK` statically, with `AppsFlyer.initSDK(devKey: (dev key), appId: (app ID))`. 

I can certainly have it pass in, say, the root application manager game object, as a third argument- does it particularly matter, in this case, as to what's being passed in?

**Comment by af-margot** [comment]
Hi @ATA-Temptress,

We are investigating the issue, we will come back as soon as we found something!

**Comment by sanuzzi** [comment]
Maybe it's related to [issue 64](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/issues/64), depending on when does firebase initializes. 
If it's before the crash, it gets notified, and if it's after the crash, the app just doesn't open an no crash is visible from firebase.

We could reproduce it following these steps on iOS:
* Open the app and enable notifications.
* Close it.
* Turn off internet, to simulate a connection problem.
* Open the app --> Apparently something fails here, maybe something with a bad format is saved on the phone. And that causes the next step:
* Reopen the app. With or without internet, it's the same --> Crash.

The only way to fix it is reinstalling the app.

@ATA-Temptress can you try to follow these steps to check if it's the same scenario?
