### ISSUE TITLE
Deeplink is not working when open URL (created from AppsFlyer.generateUserInviteLink) in iOS

### ISSUE THREAD

**Issue by mudassar024** [AppsFlyerSDK/appsflyer-unity-plugin#72]
When open url, generated from `AppsFlyer.generateUserInviteLink` , 
`onAppOpenAttributionFailure` callback occurs with message Authentication Failed.
This issue is only on Unity iOS, 
working fine in Unity android.
This was working fine for both platforms with Plugin version `6.0.7`

**Comment by af-margot** [comment]
Hi @mudassar024 , 

Thank you for reaching out!
We will investigate the issue. Which version are you using now?

**Comment by mudassar024** [comment]
`6.2.3`

**Comment by af-margot** [comment]
Hi @mudassar024, 

Unfortunately, I'm not able to reproduce the issue. 
Could you give us some details? Are you generating a long link or a short link? Are you deep linking with the app in the background or in the killed state? 
If you could share the logs you receive on the error, it would be great!
