### ISSUE TITLE
GUIDs change with updates

### ISSUE THREAD

**Issue by michalferko** [AppsFlyerSDK/appsflyer-unity-plugin#73]
Hi, when updating AppsFlyer to a newer version (6.2.2 => 6.2.41), all GUIDs change for all C# scripts and the AppsFlyerObject prefab. This might be a problem especially with references in Unity.

I noticed this must happen due to your top-level `.gitignore` that ignores `.meta` files. This should not happen with updates and it also messes up our commits with lots of unnecessary changes. The correct approach is to commit `.meta` files and to avoid having to re-generate these in every project folder.

My suggestion is for you to stop ignoring `.meta` files and commit them in this public repo.

Thanks!

**Comment by af-margot** [comment]
Hi @michalferko , 

Thank you for the input! We updated our .`gitignore`. It should work for the next release!
