### ISSUE TITLE
All installs marked as organic on ios in sdk version 6.2.41

### ISSUE THREAD

**Issue by skzloy** [AppsFlyerSDK/appsflyer-unity-plugin#76]
Hi,

We are having a strange issue on sdk version 6.2.41 on iOS platform. All installs through our campaign links marks as organic. Overall all possible installs are marked as organic. We are testing our app with available guides https://www.appsflyer.com/resources/technical-guide-to-attribution-and-deep-linking/testing-and-qa/. We are using appsflyer onelinks with defined campaign. On version 6.2.3 all worked just fine.

**Comment by af-margot** [comment]
Hi @skzloy, 

Thank you for reaching out! 
Please open a ticket to our support with logs of a fresh install and the detailed steps of the test you are doing.

**Comment by af-margot** [comment]
You can reach our support at support@appsflyer.com.

**Comment by skzloy** [comment]
Will do, thank you
