### ISSUE TITLE
Conflict with Google Firebase on iOS

### ISSUE THREAD

**Issue by Jbonavita** [AppsFlyerSDK/appsflyer-unity-plugin#80]
After I implemented this we are no longer able to get a fully working iOS build. I'm running Unity 2020.1.10f1

Here's some of the exceptions I'm seeing.

TypeLoadException: Could not resolve type with token 01000036 (from typeref, class/assembly Google.EditorInitializer, Google.VersionHandlerImpl, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.Editor.XcodeProjectPatcher' threw an exception.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <9577ac7a62ef43179789031239ba8798>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <9577ac7a62ef43179789031239ba8798>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <9577ac7a62ef43179789031239ba8798>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <9577ac7a62ef43179789031239ba8798>:0)
System.Activator.CreateInstance (System.Type type) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEditor.AssetPostprocessingInternal.GetAudioProcessorsHashString () (at /Users/bokken/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:590)
UnityEditor.AssetPostprocessingInternal:GetAudioProcessorsHashString() (at /Users/bokken/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:606)

**Comment by af-margot** [comment]
Hi @Jbonavita, 

Thank you for reaching out!
Could you clarify which version of **appsflyer-unity-plugin** you are using? Did you update from an older version or is it the first time implementing AppsFlyer plugin ?

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!
