### ISSUE TITLE
Questions regarding IAP Transaction

### ISSUE THREAD

**Issue by cihadturhan** [AppsFlyerSDK/appsflyer-unity-plugin#81]
I'm following your guides so I have two questions:

## 1
You provided following code
```cs
      string price = args.purchasedProduct.metadata.localizedPrice.ToString();
```
This will return different results based on locale ex: `1.99` or `1,99` depending on locale.
Does appsflyer normalize this value?

## 2
```cs
        string receipt = args.purchasedProduct.receipt;
        var recptToJSON = (Dictionary<string, object>)AFMiniJSON.Json.Deserialize(args.purchasedProduct.receipt);
        var transactionID = (string)recptToJSON["TransactionID"];
```
I was just using
```cs
     string transactionId = args.purchasedProduct.transactionID;
```
Do we really need to deserialize json string and read from it? Any issues with single-line above?

Thanks

**Comment by af-margot** [comment]
Hi @cihadturhan, 

1. `args.purchasedProduct.metadata.localizedPrice` should return a decimal, so with a dot as a separator. And when converting to string using `ToString()`, it should keep the dot. 
Let me know if I'm missing something or if you get a different result. 

2. This approach should work also!

**Comment by af-margot** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!
