### ISSUE TITLE
install_data response 404

### ISSUE THREAD

**Issue by XiangNanLi** [AppsFlyerSDK/appsflyer-unity-plugin#82]
I use this unityplugin (version 6.2.0), android 
But the install_data api response 400

  '''
  {"error_reason": "App ID is incorrect", "status_code": 400}
  '''
the api version is v4.0 , 
when I change version to v4 or v3, it response 

  '''
  {"af_status": "Organic", "af_message": "organic install"}
  '''

The java api is right?

**Comment by af-margot** [comment]
Hi @XiangNanLi, 

Thank you for reaching out! 
Could you check the app id used (for android, it's the package name) is the same that the one in your dashboard.

**Comment by XiangNanLi** [comment]
Thanks ,  I has solved, this is because my friends set the channel of the APP.

**Comment by XiangNanLi** [comment]
The doc is : https://support.appsflyer.com/hc/zh-cn/articles/207447023-%E5%AE%89%E5%8D%93%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%94%E7%94%A8%E5%95%86%E5%BA%97-multi-store-%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97-
