### ISSUE TITLE
OneLink custom link is not opening the App when its installed

### ISSUE THREAD

**Issue by DonCrowell** [AppsFlyerSDK/appsflyer-unity-plugin#83]
### Plugin Version
AppsFlyer SDK Version 6.2.5

### On what Platform are you having the issue?
iOS

### What did you do?
1. Have the game installed
2. Follow a deeplink on iOS

### What did you expect to happen?
Deeplink should take user to the installed app

### What happened instead?
Deeplink takes user to the App Store

### Please provide any other relevant information.
- Unity version: 2019.4.19f
- Unity 2018 works as expected on iOS
- Android works as expected

**Comment by af-margot** [comment]
Hi @DonCrowell, 
Thank you for reaching out. 
Please open a ticket to our [support team ](support@appsflyer.com) with your app id, link, if you are using universal links or URL scheme, steps taking to test. 
Thank you!
