### ISSUE TITLE
Could not find com.appsflyer:unity-wrapper:6.3.0. AppsFlyer Unity 6.2.6 package

### ISSUE THREAD

**Issue by nam2671998** [AppsFlyerSDK/appsflyer-unity-plugin#86]
[AppsFlyerBug.txt](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/files/6388675/AppsFlyerBug.txt)
Log file attached above

**Comment by DevZGA** [comment]
Same issue here

**Comment by SeriouslySam** [comment]
I believe the Editor/AppsflyerDependencies.xml should refer to 6.2.3, not to 6.3.0. Can someone from Appsflyer confirm and issue a fix for this?

**Comment by af-margot** [comment]
Yes, there is a mistake in the AppsflyerDependencies.xml. It should be `6.2.3` indeed, instead of `6.3.0`. We will fix it.
In the meantime, could you try to change it manually and see if its working ? 

You should have :
```
<?xml version="1.0" encoding="UTF-8" ?>
<dependencies>

  <androidPackages>
    <androidPackage spec="com.appsflyer:af-android-sdk:6.2.3">
    </androidPackage>
    <androidPackage spec="com.appsflyer:unity-wrapper:6.2.3">
    </androidPackage>
    <androidPackage spec="com.android.installreferrer:installreferrer:2.1">
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="AppsFlyerFramework" version="6.2.6" minTargetSdk="8.0">
    </iosPod>
  </iosPods>

</dependencies>
```

**Comment by DevZGA** [comment]
Hello af-magot.
I'm still facing the issue with the changes for 6.2.3
[AppsFlyerBug.txt](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/files/6391015/AppsFlyerBug.txt)

**Comment by SeriouslySam** [comment]
Yeah, the 6.2.3 doesn't seem to exist: https://repo.maven.apache.org/maven2/com/appsflyer/unity-wrapper/
@af-margot

**Comment by af-margot** [comment]
Hi, 
The new version was released to QA. It should be out tomorrow.
However, in the meantime, [this](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/issues/86#issuecomment-828311887) should work.

**Comment by af-margot** [comment]
Hi, 
`6.2.61` was released 
 https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/CHANGELOG.md#v6261
