### ISSUE TITLE
Version 6.2.6 doesn't compile on Unity 2018

### ISSUE THREAD

**Issue by SeriouslySam** [AppsFlyerSDK/appsflyer-unity-plugin#87]
The file Appsflyer/Editor/Appsflyer.Editor.asmdef is referring to another asmdef with a GUID. This is a Unity 2019 only feature and therefore doesn't compile on Unity 2018 anymore. This is a regression over 6.2.5, you probably shouldn't drop a support on a major Unity version on a critical bugfix patch.

Issue can be fixed by removing the reference and creating it again.

<img width="317" alt="Screenshot 2021-04-28 at 13 13 38" src="https://user-images.githubusercontent.com/15611660/116387948-015b9400-a824-11eb-9cd7-b4a75a6d7cc0.png">

<img width="317" alt="Screenshot 2021-04-28 at 13 07 36" src="https://user-images.githubusercontent.com/15611660/116387943-002a6700-a824-11eb-8fb2-2cde42207e2b.png">

**Comment by af-margot** [comment]
Hi, 
We fix it in `6.2.61` 
 https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/CHANGELOG.md#v6261
