### ISSUE TITLE
Compiler warning in the Appsflyer package

### ISSUE THREAD

**Issue by SeriouslySam** [AppsFlyerSDK/appsflyer-unity-plugin#88]
File AppsFlyer/AppsFlyerEventArgs.cs has a warning:
warning CS0168: The variable 'deepLink' is declared but never used

It seems completely unnecessary, as it defines a local variable with a same name as there's already a class variable. We've commented this out locally but it would be good to get fixed also.

**Comment by af-margot** [comment]
Hi, 
Removed in `6.2.61` 
 https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/CHANGELOG.md#v6261
