### ISSUE TITLE
AppsFlyerObject.prefab can't import to scene

### ISSUE THREAD

**Issue by ikitae** [AppsFlyerSDK/appsflyer-unity-plugin#9]
Unable to instantiate prefab. Prefab may be broken.
UnityEditorInternal.InternalEditorUtility:HierarchyWindowDrag()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Unity version : 2018.2.21f
Appsflyer unity plugin version : 5.2.1

**Comment by wesfieldj** [comment]
@ikitae Thanks for reporting the issue.

We were able to reproduce this. 
(It does not work with 2018.2.21f as you suggested by it works with > 2018.4.22f1)

We will investigate this on our end and update when we have something.

**Comment by wesfieldj** [comment]
@ikitae this was fixed in v5.3.0. 

Please let us know if you are facing any other issues with this.

Thanks!
