### ISSUE TITLE
UWP Unity support

### ISSUE THREAD

**Issue by gromilQaaaa** [AppsFlyerSDK/appsflyer-unity-plugin#90]
Hello, we are developing a Unity game for ios, android and webgl. For a few month we've also launched on windows store (UWP).

Our marketing team found that there is an AppsFlyer UWP plugin available and asked us to pick it. But looks like it requires a lot of changes directly in UWP project. This is very problematic for a CI/CD auotomation. Can you please expand Unity plugin to contain UWP?
https://support.appsflyer.com/hc/en-us/articles/207032026-Windows-and-Xbox-SDK-integration-for-developers

**Comment by af-fess** [comment]
yes, we already have a MR: https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/pull/85

**Comment by af-margot** [comment]
Hi @gromilQaaaa, 
Closing this issue as the support for UWP was added with version `6.3.0`
