### ISSUE TITLE
Errors in in-app purchase validation guide

### ISSUE THREAD

**Issue by GlebModonov-azur** [AppsFlyerSDK/appsflyer-unity-plugin#96]
If I understand correctly example code from in-app purchase validation guide has critical errors.

First of all you should not access transaction ID from deserialized dictionary by "TransactionID" key but rather use `transactionID` from `args.purchasedProduct` as mentioned in this issue #81 

So instead of:
`var transactionID = (string)recptToJSON["TransactionID"];`
It should be:
`var transactionID = args.purchasedProduct.transactionID;`

But most importantly in order to access receipt's `signature `and `purchaseData` you should deserialize receipt's payload because that's where they are.

So instead of:
```
var recptToJSON = (Dictionary<string, object>)AFMiniJSON.Json.Deserialize(args.purchasedProduct.receipt);
...
var purchaseData = (string)recptToJSON["json"];
var signature = (string)recptToJSON["signature"];
```
The code should be:
```
var recptToJSON = (Dictionary<string, object>)AFMiniJSON.Json.Deserialize(args.purchasedProduct.receipt);
var receiptPayload = (Dictionary<string, object>)AFMiniJSON.Json.Deserialize((string)recptToJSON["Payload"]);
...
var purchaseData = (string)receiptPayload["json"];
var signature = (string)receiptPayload["signature"];
```

There's probably cleaner way to deserialize the payload but I needed to get it working ASAP.

There's also a chance that I'm missing something so please correct me if that's the case.

**Comment by hanilozmen** [comment]
Yes, you are completely right @GlebModonov-azur  . Thank you for the detailed info and solution !
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/Guides.md#listeners
This document should be updated definitely based on the answer above.

**Comment by af-margot** [comment]
Thank you for the input! The documentation was updated. I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
